"""Generate scrRequestAccess: the door a new user arrives at, rebuilt dark.

This is the first screen anyone without admin sees, and until now it looked the least
finished of any of them. It now carries the same brand band, chamfered panel and status rail
as the lookup screens.

ONE DEFINITION OF "WHO AM I"

The identity lookup was written out inline eleven times across the hand-authored screen:

    LookUp(TB_Admins, (Lower(Person.Claims) = "i:0#.f|membership|" & Lower(User().Email)
                       || Lower(Person.Email) = Lower(User().Email)))

Eleven copies of the one expression whose exact shape was hard-won - it matches on Claims
because User().Email is the UPN while a SharePoint Person column stores the mail attribute,
and those differ at Glory. Any future correction had eleven places to reach. It is now
written once in this generator and interpolated.

WHY THE PAGE STILL RE-READS THE LIST INSTEAD OF TRUSTING varIsAdmin

varIsAdmin is set once in App.OnStart. Someone approved while the app is open would keep
seeing the request page, so every control here reads TB_Admins live. "Check again" exists
for exactly that gap: it re-runs the lookup, sets varIsAdmin, and leaves if it now passes.
That is the whole reason the button is on the screen and why it is not decoration.

FOUR STATES, ONE VOICE

No row, Pending, Approved, Denied. Each states what is true and what the person can do next;
none of them relies on colour alone.
"""
from pathlib import Path
import screen_parts as P

OUT = Path(r"E:\Papp\powerappgoofing\app\screens\scrRequestAccess.pa.yaml")

# Matches on Claims because User().Email is the UPN and a SharePoint Person column stores
# the mail attribute; at Glory those are different strings. Email is kept as a fallback for
# tenants where they agree. See 00_Setup.md.
ME = ("LookUp(TB_Admins, (Lower(Person.Claims) = \"i:0#.f|membership|\" & Lower(User().Email)"
      " || Lower(Person.Email) = Lower(User().Email)))")
STATUS = f'Coalesce({ME}.Status.Value, "")'

PANEL_H = 188

BODY = f'''=Switch({STATUS},
                        "Pending",
                        "Your request is waiting for an admin to approve it. Nothing will change here until they do.",
                        "Approved",
                        "You have admin access. If the Admin button is still missing, press Check again - the app reads your role once at startup.",
                        "Denied",
                        "Your request was not approved. You can ask again below if that was a mistake.",
                        "Admin covers adding customers, machines and documents. Most technicians never need it - everything else in the app works without it."
                    )'''

doc = f'''# Screen — Request access  (GENERATED by scripts/gen_request_access.py)
#
# The first screen a user without admin sees. Every control reads TB_Admins live rather than
# trusting varIsAdmin, which App.OnStart sets once - see the generator docstring.

Screens:
  scrRequestAccess:
    Properties:
      Fill: =AppDark.Bg
    Children:
      - conRootReq:
          Control: GroupContainer
          Variant: ManualLayout
          Properties:
            X: =0
            Y: =0
            Width: =Parent.Width
            Height: =Parent.Height
            Fill: =AppDark.Bg
          Children:
{P.brand_band("Req", "scrHome", back_transition="CoverRight", back_label="Home")}

            - lblTitleReq:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter
                  Y: ={P.BAND} + 24
                  Width: ={P.CW}
                  Height: =41
                  Text: ="Admin access"
                  Font: =AppFont
                  Size: =If(IsNarrow, AppType.Title, AppType.Display)
                  FontWeight: =FontWeight.Semibold
                  Color: =AppDark.Fg
                  Wrap: =false
                  AutoHeight: =false

            # Chamfered panel with a rail coloured by where the request stands. Same shape
            # as the version hero, because this screen answers a status question too.
            - imgReqPanel:
                Control: Image
                Properties:
                  X: =Gutter
                  Y: =lblTitleReq.Y + lblTitleReq.Height + Gutter
                  Width: =Min({P.CW}, {P.PANEL_MAX})
                  Height: ={PANEL_H}
                  Image: |
                    ="data:image/svg+xml;utf8, " & EncodeUrl(
                        "<svg xmlns='http://www.w3.org/2000/svg' width='" & Round(Min({P.CW}, {P.PANEL_MAX}), 0) & "' height='{PANEL_H}' viewBox='0 0 " & Round(Min({P.CW}, {P.PANEL_MAX}), 0) & " {PANEL_H}' preserveAspectRatio='none'>" &
                        "<path d='M0 0 H" & Round(Min({P.CW}, {P.PANEL_MAX}) - 20, 0) & " L" & Round(Min({P.CW}, {P.PANEL_MAX}), 0) & " 20 V{PANEL_H} H0 Z' fill='#171A21' stroke='#2A2F3A' stroke-width='1'/>" &
                        "<rect x='0' y='0' width='4' height='{PANEL_H}' fill='" &
                        Switch({STATUS}, "Approved", "#3DD68C", "Denied", "#F5B83D", "Pending", "#6A73E6", "#2A2F3A") & "'/>"
                    )

            # The state in a word. Says "Not requested" rather than going blank when there is
            # no row, because a blank chip reads as a screen that failed to load.
            - lblReqStatus:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter + 24
                  Y: =imgReqPanel.Y + 22
                  Width: =200
                  Height: =26
                  Align: =Align.Center
                  VerticalAlign: =VerticalAlign.Middle
                  Font: =AppFont
                  Size: =AppType.Small
                  FontWeight: =FontWeight.Bold
                  Wrap: =false
                  AutoHeight: =false
                  RadiusTopLeft: =6
                  RadiusTopRight: =6
                  RadiusBottomLeft: =6
                  RadiusBottomRight: =6
                  Text: |
                    =Upper(Coalesce({STATUS}, "Not requested"))
                  Color: |
                    =Switch({STATUS}, "Approved", AppDark.Ok, "Denied", AppDark.Warn, AppDark.Fg)
                  Fill: |
                    =Switch({STATUS}, "Approved", AppDark.OkTint, "Denied", AppDark.WarnTint, AppDark.NeutralTint)

            - lblReqBody:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter + 24
                  Y: =imgReqPanel.Y + 60
                  Width: =Min({P.CW}, {P.PANEL_MAX}) - 48
                  Height: =56
                  Font: =AppFont
                  Size: =AppType.Body
                  Color: =AppDark.FgSecondary
                  Wrap: =true
                  AutoHeight: =false
                  Text: |
                    {BODY}

            - btnRequest:
                Control: ModernButton
                Properties:
                  Appearance: =ButtonAppearance.Primary
                  Text: |
                    =If({STATUS} = "Denied", "Ask again", "Request admin access")
                  Font: =AppFont
                  Size: =AppType.Body
                  FontWeight: =FontWeight.Semibold
                  BorderThickness: =0
                  Height: =44
                  Width: =240
                  X: =Gutter + 24
                  Y: =imgReqPanel.Y + 126
                  RadiusTopLeft: =6
                  RadiusTopRight: =6
                  RadiusBottomLeft: =6
                  RadiusBottomRight: =6
                  Visible: |
                    ={STATUS} <> "Pending" && {STATUS} <> "Approved"
                  # Upsert, not insert. A person who was denied and asks again must update
                  # their existing row; patching a second one leaves an admin looking at two
                  # requests from the same person with no way to tell which is current.
                  OnSelect: |
                    =IfError(
                        If(
                            IsBlank({ME}),
                            Patch(TB_Admins, Defaults(TB_Admins),
                                {{
                                    Title: User().FullName,
                                    Person:
                                        {{
                                            '@odata.type': "#Microsoft.Azure.ActiveDirectory.Connectors.Model.GraphUser",
                                            Claims: "i:0#.f|membership|" & Lower(User().Email),
                                            DisplayName: User().FullName,
                                            Email: User().Email,
                                            Department: "",
                                            JobTitle: "",
                                            Picture: ""
                                        }},
                                    Status: {{ Value: "Pending" }}
                                }}
                            ),
                            Patch(TB_Admins, {ME}, {{ Status: {{ Value: "Pending" }} }})
                        );
                        Refresh(TB_Admins);
                        Notify("Request sent. An admin will review it.", NotificationType.Success),
                        Notify("Could not send the request: " & FirstError.Message, NotificationType.Error)
                    )

            # The gap this closes: varIsAdmin is read once at startup, so an approval granted
            # while the app is open is invisible until something re-reads the list.
            - btnRecheck:
                Control: ModernButton
                Properties:
                  Appearance: =ButtonAppearance.Outline
                  Text: ="Check again"
                  Font: =AppFont
                  Size: =AppType.Body
                  FontWeight: =FontWeight.Semibold
                  Color: =AppDark.Accent
                  BorderColor: =AppDark.Line
                  BorderThickness: =1
                  Height: =44
                  Width: =160
                  X: |
                    =Gutter + 24 + If({STATUS} <> "Pending" && {STATUS} <> "Approved", 252, 0)
                  Y: =imgReqPanel.Y + 126
                  RadiusTopLeft: =6
                  RadiusTopRight: =6
                  RadiusBottomLeft: =6
                  RadiusBottomRight: =6
                  OnSelect: |
                    =Refresh(TB_Admins);
                    Set(varIsAdmin, !IsBlank(LookUp(TB_Admins, (Lower(Person.Claims) = "i:0#.f|membership|" & Lower(User().Email) || Lower(Person.Email) = Lower(User().Email)) && Status.Value = "Approved")));
                    If(varIsAdmin, Navigate(scrHome, ScreenTransition.CoverRight), Notify("Still not approved.", NotificationType.Information))

            - lblReqWho:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter
                  Y: =imgReqPanel.Y + {PANEL_H} + Gutter
                  Width: ={P.CW}
                  Height: =20
                  Font: =AppFont
                  Size: =AppType.Small
                  Color: =AppDark.Muted
                  Wrap: =false
                  AutoHeight: =false
                  Text: |
                    ="Signed in as " & User().Email
'''

OUT.write_text(doc, encoding="utf-8", newline="")
print(f"wrote {OUT}  ({len(doc.splitlines())} lines)")
