"""Generate scrCustomers: the site list, rebuilt dark.

WHAT IT GAINS: A REASON TO SCAN IT

Rows were a name and a description. That answers "which site" and nothing else, so the only
way to learn whether a site needed attention was to open it. Each row now carries a count of
machines whose version nobody has confirmed in over a year, or ever - the sites where what
the app says is least likely to still be true.

WHY IT NEVER SAYS "ALL GOOD"

The row warns when something needs checking and stays quiet otherwise. It deliberately does
NOT render a green "up to date" state, because this data cannot support that claim: the app
does not read machines, so a recently verified record and a lucky guess are the same shape
here. Silence means "nothing known to be wrong", which is what is actually true.

That choice also halves the work per row - see below.

COST PER ROW

The check-count is a Filter with a nested LookUp per installation, which SharePoint cannot
delegate; it runs client-side against the row limit. That is one such count per customer
rendered, plus one cheap solution count. Acceptable for a branch list in the tens, and worth
watching if TB_Customers grows into the hundreds - the fix then is a rollup column
maintained by the wizard rather than a per-row scan here.

Units carry Customer as well as Parent (confirmed in the seed data and in gen_onboard's
child Patch), so one filter on Customer.Id sees every machine at a site without walking the
parent chain.
"""
from pathlib import Path
import screen_parts as P

OUT = Path(r"E:\Papp\powerappgoofing\app\screens\scrCustomers.pa.yaml")

# The one creation point that cannot start from the thing above it: a customer has no page
# until it exists, so it is added from the list of its siblings.
ACTIONS = [("btnAddCust", "+  Add a customer",
            P.admin_open("Cust", "Defaults(TB_Customers)", True, back="scrCustomers"), 168)]

CARD_H = 76

# Machines at this site nobody has confirmed within a year, or ever.
#
# The date has to follow whichever source supplied the version - a machine's own record
# beats the site default - so this mirrors screen_parts.effective_verified rather than
# reading one column. A gallery row has no local name to bind it to, which is why the
# expression is spelled out here instead of shared; the threshold itself is not duplicated,
# it comes from screen_parts.
_VER = ("If(!IsBlank(I.'Installed Version'), I.'Last Verified', "
        "LookUp(TB_SoftwareVersions, Customer.Id = ThisItem.ID "
        "&& Product.Id = I.Product.Id).'Last Verified')")

CHECK = ("CountRows(Filter(TB_Installations As I, I.Customer.Id = ThisItem.ID, "
         "I.Status.Value <> \"Retired\", "
         f"{P.verified_needs_check(_VER)}))")

# Solutions only: installations with no Parent. Cheap, and the number a technician thinks in.
SOL_N = ("CountRows(Filter(TB_Installations, Customer.Id = ThisItem.ID, "
         "IsBlank(ThisRecord.'Parent'), Status.Value <> \"Retired\"))")

doc = f'''# Screen — Customers  (GENERATED by scripts/gen_customers.py — edit the generator)
#
# The site list. Rows warn when a site has machines nobody has verified lately and stay quiet
# otherwise - never a green "all good", because an unsurveyed site is indistinguishable from
# a current one in this data. See the generator docstring.
#
# Selecting a row sets varCustomer and hands off to scrCustomerOverview.

Screens:
  scrCustomers:
    Properties:
      Fill: =AppDark.Bg
    Children:
      - conRootCus:
          Control: GroupContainer
          Variant: ManualLayout
          Properties:
            X: =0
            Y: =0
            Width: =Parent.Width
            Height: =Parent.Height
            Fill: =AppDark.Bg
          Children:
{P.brand_band("Cus", "scrHome", back_transition="CoverRight", back_label="Home")}

{P.title_actions("lblTitleCus", ACTIONS)}            - lblTitleCus:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter
                  Y: ={P.BAND} + 24
                  Width: ={P.title_shrink(ACTIONS)}
                  Height: ={P.title_height()}
                  Text: ="Customers"
                  Font: =AppFont
                  Size: =If(IsNarrow, AppType.Title, AppType.Display)
                  FontWeight: =FontWeight.Semibold
                  Color: =AppDark.Fg
                  Wrap: =false
                  AutoHeight: =false
            # Says how many rows the search is showing, so an empty-looking list reads as a
            # narrow search rather than as missing data.
            - lblSubtitleCus:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter
                  Y: =lblTitleCus.Y + lblTitleCus.Height
                  Width: ={P.CW}
                  Height: =22
                  Font: =AppFont
                  Size: =AppType.Body
                  Color: =AppDark.FgSecondary
                  Wrap: =false
                  AutoHeight: =false
                  Text: |
                    =CountRows(galCustomers.AllItems) & If(Len(Trim(txtSearchCus.Text)) > 0, " matching", " active") & " site(s)"

            - txtSearchCus:
                Control: ModernTextInput
                Properties:
                  Type: =TextInputType.Search
                  X: =Gutter
                  Y: =lblSubtitleCus.Y + lblSubtitleCus.Height + Gutter
                  Width: =Min({P.CW}, {P.PANEL_MAX})
                  Height: =48
                  Default: =""
                  Placeholder: ="Search customers"
                  Font: =AppFont
                  Size: =AppType.Body
                  Color: =AppDark.Fg
                  Fill: =AppDark.Surface
                  BorderColor: =AppDark.Line
                  BorderThickness: =1
                  RadiusTopLeft: =6
                  RadiusTopRight: =6
                  RadiusBottomLeft: =6
                  RadiusBottomRight: =6

            - galCustomers:
                Control: Gallery
                Variant: Vertical
                Properties:
                  X: =Gutter
                  Y: =txtSearchCus.Y + txtSearchCus.Height + Gutter
                  Width: ={P.CW}
                  Height: =Max(Parent.Height - (txtSearchCus.Y + txtSearchCus.Height + Gutter) - Gutter, {CARD_H})
                  TemplateSize: ={CARD_H + 10}
                  TemplatePadding: =0
                  ShowScrollbar: =true
                  Items: |
                    =SortByColumns(
                        Filter(
                            TB_Customers,
                            Active = true,
                            StartsWith(Title, Trim(txtSearchCus.Text))
                        ),
                        "Title",
                        SortOrder.Ascending
                    )
                  OnSelect: |
                    =Set(varCustomer, ThisItem);
                    Navigate(scrCustomerOverview, ScreenTransition.Cover)
                Children:
                  - imgCardCus:
                      Control: Image
                      Properties:
                        X: =0
                        Y: =0
                        Width: =Parent.TemplateWidth
                        Height: ={CARD_H}
                        Image: |
                          ="data:image/svg+xml;utf8, " & EncodeUrl(
                              "<svg xmlns='http://www.w3.org/2000/svg' width='" & Round(Parent.TemplateWidth, 0) & "' height='{CARD_H}' viewBox='0 0 " & Round(Parent.TemplateWidth, 0) & " {CARD_H}' preserveAspectRatio='none'>" &
                              "<path d='M0 0 H" & Round(Parent.TemplateWidth - 14, 0) & " L" & Round(Parent.TemplateWidth, 0) & " 14 V{CARD_H} H0 Z' fill='#171A21' stroke='#2A2F3A' stroke-width='1'/>" &
                              "</svg>"
                          )
                  # CHECK is a non-delegable Filter with a nested LookUp per installation,
                  # so it is evaluated ONCE per row here and read back by the two controls
                  # that need it. Referencing a sibling inside the same gallery template is
                  # row-scoped, which is the same hidden-label idiom used for ForAll over
                  # AllItems elsewhere in this app.
                  - lblCheckCalcCus:
                      Control: ModernText
                      Properties:
                        PaddingTop: =0
                        PaddingBottom: =0
                        OnSelect: =Select(Parent)
                        X: =0
                        Y: =0
                        Width: =1
                        Height: =1
                        Visible: =false
                        Font: =AppFont
                        Size: =AppType.Small
                        Color: =AppDark.Muted
                        Text: |
                          ={CHECK}

                  # Amber only when something is known to need checking. Neutral otherwise -
                  # never green, because a verified record and an unexamined one are the
                  # same shape here and only one of them deserves reassurance.
                  - recCardRailCus:
                      Control: Rectangle
                      Properties:
                        OnSelect: =Select(Parent)
                        X: =0
                        Y: =0
                        Width: =4
                        Height: ={CARD_H}
                        Fill: |
                          =If(Value(lblCheckCalcCus.Text) > 0, AppDark.Warn, AppDark.Line)
                  - lblName:
                      Control: ModernText
                      Properties:
                        PaddingTop: =0
                        PaddingBottom: =0
                        OnSelect: =Select(Parent)
                        X: =20
                        Y: =14
                        Width: =(Parent.TemplateWidth - 40) * 0.62
                        Height: =26
                        Text: =ThisItem.Title
                        Font: =AppFont
                        Size: =AppType.Heading
                        FontWeight: =FontWeight.Semibold
                        Color: =AppDark.Fg
                        Wrap: =false
                        AutoHeight: =false
                  - lblDesc:
                      Control: ModernText
                      Properties:
                        PaddingTop: =0
                        PaddingBottom: =0
                        OnSelect: =Select(Parent)
                        X: =20
                        Y: =42
                        Width: =(Parent.TemplateWidth - 40) * 0.62
                        Height: =20
                        Font: =AppFont
                        Size: =AppType.Small
                        Color: =AppDark.Muted
                        Wrap: =false
                        AutoHeight: =false
                        Text: |
                          ={SOL_N} & " solution(s)" & If(IsBlank(ThisItem.Description), "", "  ·  " & ThisItem.Description)
                  # Conditional Text rather than Visible + Text: CHECK is a non-delegable
                  # Filter with a nested LookUp per installation, and a separate Visible
                  # would evaluate it a third time on every row for no visual difference.
                  - lblCheckCus:
                      Control: ModernText
                      Properties:
                        PaddingTop: =0
                        PaddingBottom: =0
                        OnSelect: =Select(Parent)
                        X: =20 + ((Parent.TemplateWidth - 40) * 0.62)
                        Y: =28
                        Width: =(Parent.TemplateWidth - 40) * 0.38 - 10
                        Height: =22
                        Align: =Align.Right
                        Font: =AppFont
                        Size: =AppType.Body
                        FontWeight: =FontWeight.Semibold
                        Color: =AppDark.Warn
                        Wrap: =false
                        AutoHeight: =false
                        Text: |
                          =If(Value(lblCheckCalcCus.Text) > 0, lblCheckCalcCus.Text & " to check", "")
                  - galCustomersHit:
                      Control: Classic/Button
                      Properties:
                        OnSelect: =Select(Parent)
                        X: =0
                        Y: =0
                        Width: =Parent.TemplateWidth
                        Height: ={CARD_H}
                        Text: =""
                        Fill: =RGBA(0, 0, 0, 0)
                        HoverFill: =RGBA(106, 115, 230, 0.10)
                        PressedFill: =RGBA(106, 115, 230, 0.18)
                        BorderThickness: =0
                        HoverBorderColor: =RGBA(0, 0, 0, 0)
                        PressedBorderColor: =RGBA(0, 0, 0, 0)
                        FocusedBorderThickness: =2
                        FocusedBorderColor: =AppDark.Accent
            - lblNoCustomers:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter
                  Y: =galCustomers.Y
                  Width: ={P.CW}
                  Height: =40
                  Font: =AppFont
                  Size: =AppType.Body
                  Color: =AppDark.Muted
                  Visible: =CountRows(galCustomers.AllItems) = 0
                  Text: |
                    =If(Len(Trim(txtSearchCus.Text)) > 0, "No customers start with """ & Trim(txtSearchCus.Text) & """.", "No active customers are on file.")
'''

OUT.write_text(doc, encoding="utf-8", newline="")
print(f"wrote {OUT}  ({len(doc.splitlines())} lines)")
