"""Generate scrCatalogue: the model list, rebuilt dark.

This is the only route to a document without a customer in context - a technician who knows
the machine but not the site. It reads neither varCustomer nor varInstallation.

MASTER-DETAIL, AND WHY THE SELECTION IS MARKED HERE

Tapping a model sets varExpandedModel and fills the document panel beside it; nothing
navigates. That selection PERSISTS and drives what the rest of the screen shows, so the
selected card carries an accent rail and a lifted surface.

That is the exact opposite of the treatment removed from the other galleries earlier, and
deliberately so. There, tapping navigated away, so nothing persisted - and because a canvas
gallery selects its first row on load, styling from ThisItem.IsSelected made row one look
pre-chosen before anyone touched it. Here the state is a variable that starts at 0, so
nothing is marked until a person marks it, and leaving it unmarked would mean a document
panel with no visible source.

THE DOCUMENT PANEL NAMES ITS MODEL

"DOCUMENTS" alone left the panel orphaned, especially in the stacked layout where it sits
below a scrolling list and the selected row may be out of view. It now reads
"DOCUMENTS · CI 300X".

Rows omit the owning product when the document belongs to the model being viewed - printing
"CI 300X" on every row of the CI 300X panel is noise - and name it when the document comes
from a unit the model can take, which is the case where it carries real information.

WHAT IS SCOPED HOW

The list widens to units via TB_SolutionUnits: the catalogue describes what a model CAN
take, not what any site has fitted. Customer-specific documents are excluded entirely
(IsBlank(Customer)) - this screen has no customer, so a document written for one site would
be shown with nothing to say whose it is.
"""
from pathlib import Path
import screen_parts as P

OUT = Path(r"E:\Papp\powerappgoofing\app\screens\scrCatalogue.pa.yaml")

# The root of the second hierarchy. A peripheral is not a special case here: a printer or a
# palm vein reader is a model with a different Product Type, added exactly like any other.
ACTIONS = [("btnAddModelCat", "+  Add a model",
            P.admin_open("Prod", "Defaults(TB_Products)", True, back="scrCatalogue"), 152)]

CARD_H = 82
EXPANDED = "!IsBlank(varExpandedModel) && varExpandedModel <> 0"
SELECTED = "ThisItem.ID = varExpandedModel"
DOC_N = "CountRows(Filter(TB_References, Product.Id = ThisItem.ID, IsBlank(Customer)))"

# Universal references for the selected model, or for any unit that model can take.
# "As R" names the outer row so R.Product.Id survives the nested Filter's own scope.
ITEMS = """=SortByColumns(
                        Filter(
                            TB_References As R,
                            IsBlank(R.Customer),
                            R.Product.Id = varExpandedModel
                            || CountRows(
                                   Filter(
                                       TB_SolutionUnits,
                                       Solution.Id = varExpandedModel,
                                       Unit.Id = R.Product.Id
                                   )
                               ) > 0
                        ),
                        "Title",
                        SortOrder.Ascending
                    )"""

META = ('=ThisItem.Section.Value & "  ·  " & ThisItem.\'Reference Type\'.Value & '
        'If(ThisItem.Product.Id = varExpandedModel, "", '
        '"  ·  " & LookUp(TB_Products, ID = ThisItem.Product.Id).Title)')

# Side by side once there is room; stacked below the list otherwise.
WIDE = "scrCatalogue.Size >= ScreenSize.Large"
LIST_Y = "txtSearchCat.Y + txtSearchCat.Height + Gutter"
# No leading "=" - ref_gallery supplies it. A second one produced "Y: ==If(...)".
DOCS_Y = f"If({WIDE}, lblModelsHeadingCat.Y, Parent.Height - Gutter - 250)"

doc = f'''# Screen — Catalogue  (GENERATED by scripts/gen_catalogue.py — edit the generator)
#
# Models and their documents, with no customer in context. Selecting a model sets
# varExpandedModel and fills the panel beside it rather than navigating - see the generator
# docstring for why the selection is visibly marked here when it was removed elsewhere.
#
# varExpandedModel starts at 0 in App.OnStart, so nothing is selected on entry.

Screens:
  scrCatalogue:
    Properties:
      Fill: =AppDark.Bg
      OnVisible: =Set(varExpandedModel, 0)
    Children:
      - conRootCat:
          Control: GroupContainer
          Variant: ManualLayout
          Properties:
            X: =0
            Y: =0
            Width: =Parent.Width
            Height: =Parent.Height
            Fill: =AppDark.Bg
          Children:
{P.brand_band("Cat", "scrHome", back_transition="CoverRight", back_label="Home")}

{P.title_actions("lblTitleCat", ACTIONS)}            - lblTitleCat:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter
                  Y: ={P.BAND} + 24
                  Width: ={P.title_shrink(ACTIONS)}
                  Height: ={P.title_height()}
                  Text: ="Catalogue"
                  Font: =AppFont
                  Size: =If(IsNarrow, AppType.Title, AppType.Display)
                  FontWeight: =FontWeight.Semibold
                  Color: =AppDark.Fg
                  Wrap: =false
                  AutoHeight: =false
            - lblSubtitleCat:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter
                  Y: =lblTitleCat.Y + lblTitleCat.Height
                  Width: ={P.CW}
                  Height: =22
                  Font: =AppFont
                  Size: =AppType.Body
                  Color: =AppDark.FgSecondary
                  Wrap: =false
                  AutoHeight: =false
                  Text: |
                    =CountRows(galModels.AllItems) & If(Len(Trim(txtSearchCat.Text)) > 0, " matching", " active") & " model(s)"

            - txtSearchCat:
                Control: ModernTextInput
                Properties:
                  Type: =TextInputType.Search
                  X: =Gutter
                  Y: =lblSubtitleCat.Y + lblSubtitleCat.Height + Gutter
                  Width: =Min({P.CW}, {P.PANEL_MAX})
                  Height: =48
                  Default: =""
                  Placeholder: ="Search models"
                  Font: =AppFont
                  Size: =AppType.Body
                  Color: =AppDark.Fg
                  Fill: =AppDark.Surface
                  BorderColor: =AppDark.Line
                  BorderThickness: =1
                  RadiusTopLeft: =6
                  RadiusTopRight: =6
                  RadiusBottomLeft: =6
                  RadiusBottomRight: =6

            - lblModelsHeadingCat:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter
                  Y: ={LIST_Y}
                  Width: ={P.CW}
                  Height: =22
                  Text: ="MODELS"
                  Font: =AppFont
                  Size: =AppType.Small
                  FontWeight: =FontWeight.Bold
                  Color: =AppDark.Muted
            - galModels:
                Control: Gallery
                Variant: Vertical
                Properties:
                  X: =Gutter
                  Y: =lblModelsHeadingCat.Y + lblModelsHeadingCat.Height + 10
                  # Half width beside the panel once there is room; full width above it
                  # when stacked.
                  Width: |
                    =If({WIDE}, ({P.CW} - Gutter) / 2, {P.CW})
                  Height: |
                    =If(
                        {WIDE},
                        Max(Parent.Height - (lblModelsHeadingCat.Y + lblModelsHeadingCat.Height + 10) - Gutter, {CARD_H}),
                        Max(Parent.Height - (lblModelsHeadingCat.Y + lblModelsHeadingCat.Height + 10) - Gutter - If({EXPANDED}, 250 + Gutter, 0), {CARD_H})
                    )
                  TemplateSize: ={CARD_H + 10}
                  TemplatePadding: =0
                  ShowScrollbar: =true
                  Items: |
                    =SortByColumns(
                        Filter(
                            TB_Products,
                            Active = true,
                            StartsWith(Title, Trim(txtSearchCat.Text))
                        ),
                        "Title",
                        SortOrder.Ascending
                    )
                  OnSelect: =Set(varExpandedModel, ThisItem.ID)
                Children:
                  # The selected card lifts to SurfaceAlt and keeps its chamfer; the rail
                  # is what actually reads at a glance.
                  - imgCardCat:
                      Control: Image
                      Properties:
                        X: =0
                        Y: =0
                        Width: =Parent.TemplateWidth
                        Height: ={CARD_H}
                        Image: |
                          ="data:image/svg+xml;utf8, " & EncodeUrl(
                              "<svg xmlns='http://www.w3.org/2000/svg' width='" & Round(Parent.TemplateWidth, 0) & "' height='{CARD_H}' viewBox='0 0 " & Round(Parent.TemplateWidth, 0) & " {CARD_H}' preserveAspectRatio='none'>" &
                              "<path d='M0 0 H" & Round(Parent.TemplateWidth - 14, 0) & " L" & Round(Parent.TemplateWidth, 0) & " 14 V{CARD_H} H0 Z' fill='" &
                              If({SELECTED}, "#1E222B", "#171A21") & "' stroke='" &
                              If({SELECTED}, "#6A73E6", "#2A2F3A") & "' stroke-width='1'/>" &
                              "</svg>"
                          )
                  - recCardRailCat:
                      Control: Rectangle
                      Properties:
                        OnSelect: =Select(Parent)
                        X: =0
                        Y: =0
                        Width: =4
                        Height: ={CARD_H}
                        Fill: =If({SELECTED}, AppDark.Accent, AppDark.Line)
                  - lblModelTitle:
                      Control: ModernText
                      Properties:
                        PaddingTop: =0
                        PaddingBottom: =0
                        OnSelect: =Select(Parent)
                        X: =20
                        Y: =14
                        Width: =(Parent.TemplateWidth - 40) * 0.62
                        Height: =26
                        Text: =ThisItem.Title
                        Font: =AppFont
                        Size: =AppType.Heading
                        FontWeight: =FontWeight.Semibold
                        Color: =AppDark.Fg
                        Wrap: =false
                        AutoHeight: =false
                  - lblModelType:
                      Control: ModernText
                      Properties:
                        PaddingTop: =0
                        PaddingBottom: =0
                        OnSelect: =Select(Parent)
                        X: =20
                        Y: =44
                        Width: =(Parent.TemplateWidth - 40) * 0.62
                        Height: =20
                        Font: =AppFont
                        Size: =AppType.Small
                        Color: =AppDark.Muted
                        Wrap: =false
                        AutoHeight: =false
                        Text: |
                          =ThisItem.'Product Type'.Value & "  ·  " & {DOC_N} & " document(s)"
                  # The standard version is the one fact a catalogue exists to publish, so
                  # it gets the right-hand column that versions occupy everywhere else in
                  # this app.
                  - lblStandardCat:
                      Control: ModernText
                      Properties:
                        PaddingTop: =0
                        PaddingBottom: =0
                        OnSelect: =Select(Parent)
                        X: =20 + ((Parent.TemplateWidth - 40) * 0.62)
                        Y: =20
                        Width: =(Parent.TemplateWidth - 40) * 0.38 - 10
                        Height: =22
                        Align: =Align.Right
                        Font: =AppFont
                        Size: =AppType.Body
                        FontWeight: =FontWeight.Semibold
                        Wrap: =false
                        AutoHeight: =false
                        Text: =Coalesce(ThisItem.'Current Standard Version', "no standard set")
                        Color: =If(IsBlank(ThisItem.'Current Standard Version'), AppDark.Faint, AppDark.Fg)
                  - lblStandardCaption:
                      Control: ModernText
                      Properties:
                        PaddingTop: =0
                        PaddingBottom: =0
                        OnSelect: =Select(Parent)
                        X: =20 + ((Parent.TemplateWidth - 40) * 0.62)
                        Y: =44
                        Width: =(Parent.TemplateWidth - 40) * 0.38 - 10
                        Height: =18
                        Align: =Align.Right
                        Text: ="standard"
                        Font: =AppFont
                        Size: =AppType.Small
                        Color: =AppDark.Muted
                        Wrap: =false
                        AutoHeight: =false
                  - galModelsHit:
                      Control: Classic/Button
                      Properties:
                        OnSelect: =Select(Parent)
                        X: =0
                        Y: =0
                        Width: =Parent.TemplateWidth
                        Height: ={CARD_H}
                        Text: =""
                        Fill: =RGBA(0, 0, 0, 0)
                        HoverFill: =RGBA(106, 115, 230, 0.10)
                        PressedFill: =RGBA(106, 115, 230, 0.18)
                        BorderThickness: =0
                        HoverBorderColor: =RGBA(0, 0, 0, 0)
                        PressedBorderColor: =RGBA(0, 0, 0, 0)
                        FocusedBorderThickness: =2
                        FocusedBorderColor: =AppDark.Accent
            - lblNoModels:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter
                  Y: =galModels.Y
                  Width: ={P.CW}
                  Height: =40
                  Font: =AppFont
                  Size: =AppType.Body
                  Color: =AppDark.Muted
                  Visible: =CountRows(galModels.AllItems) = 0
                  Text: |
                    =If(Len(Trim(txtSearchCat.Text)) > 0, "No models start with """ & Trim(txtSearchCat.Text) & """.", "No active models are on file.")

            # ---- document panel
            # Named after the selected model, because when stacked it sits below a scrolling
            # list and the row it belongs to may be out of view.
            - lblPromptCat:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: |
                    =If({WIDE}, Gutter + (({P.CW} - Gutter) / 2) + Gutter, Gutter)
                  Y: =lblModelsHeadingCat.Y
                  Width: |
                    =If({WIDE}, ({P.CW} - Gutter) / 2, {P.CW})
                  Height: =40
                  Text: ="Select a model to see its documents."
                  Font: =AppFont
                  Size: =AppType.Body
                  Color: =AppDark.Muted
                  Visible: =!({EXPANDED})
{P.ref_gallery("Docs", "Cat", '="DOCUMENTS  ·  " & LookUp(TB_Products, ID = varExpandedModel).Title', "No universal documents are on file for this model.", DOCS_Y, ITEMS, meta=META, height=f"=If({WIDE}, Max(Parent.Height - lblDocsHeadingCat.Y - 32 - Gutter, 60), 250)", visible=f"={EXPANDED} && CountRows(galDocsCat.AllItems) > 0", empty_visible=f"={EXPANDED} && CountRows(galDocsCat.AllItems) = 0", x=f"=If({WIDE}, Gutter + (({P.CW} - Gutter) / 2) + Gutter, Gutter)", width=f"=If({WIDE}, ({P.CW} - Gutter) / 2, {P.CW})")}
'''

OUT.write_text(doc, encoding="utf-8", newline="")
print(f"wrote {OUT}  ({len(doc.splitlines())} lines)")
