"""Generate scrUnit: the single-unit detail screen, rebuilt dark.

scrUnit and scrSolution answer the same question about different records - "is this on the
current build?" - so they share the brand band, the version hero, the config panel and the
document lists, all from screen_parts.py. Generating both from one set of fragments is the
point: the hand-written versions had already drifted, with the same separator rendered at
three different spacings and the two version panels built from different control counts.

WHAT IS DIFFERENT HERE

1. A BREADCRUMB. A unit is only ever reached through a customer and a solution, and the
   model number alone ("SDRB250") does not say which site or which machine it is fitted to.
   The trail carries that, and it is the one piece of context this screen cannot derive from
   its own title.

2. NO UNITS LIST. This IS a unit. Nothing hangs below it.

3. DOCUMENTS ARE NOT WIDENED. scrSolution deliberately gathers references for the machine
   and for every unit fitted under it, because a technician at a CI 300X needs the SDRB250's
   manual too. Here the scope is exactly this product - widening would pull in siblings that
   have nothing to do with the unit on screen.

4. BACK RESTORES THE PARENT. varInstallation currently holds the unit; the solution screen
   expects the solution, so the button re-points the variable before navigating. That was
   already true and is preserved verbatim - it is the one piece of state juggling on this
   screen and the easiest thing to break silently.

STANDARD VERSION COMES FROM THE UNIT'S OWN PRODUCT, never the parent solution's. Comparing a
note recycler against a coin recycler's standard would produce a confident wrong answer,
which is worse than no answer.
"""
from pathlib import Path
import screen_parts as P

OUT = Path(r"E:\Papp\powerappgoofing\app\screens\scrUnit.pa.yaml")

# A unit has nothing beneath it, so its title row offers only the correction - which is the
# most common admin task in the app: a version moved and someone is standing in front of it.
ACTIONS = [("btnEditUnit", "",
            P.admin_open("Inst", "varInstallation", False, back="scrUnit"), 44)]

PROD = "LookUp(TB_Products, ID = varInstallation.Product.Id)"
PARENT_PROD = ("LookUp(TB_Products, ID = LookUp(TB_Installations, "
               "ID = varInstallation.'Parent'.Id).Product.Id)")

BACK = ("Set(varInstallation, LookUp(TB_Installations, ID = varInstallation.'Parent'.Id)); "
        "Navigate(scrSolution, ScreenTransition.CoverRight)")


def refs(section):
    """References for this unit's product only. See the docstring on scoping."""
    return f"""=SortByColumns(
                        Filter(
                            TB_References,
                            Product.Id = varInstallation.Product.Id,
                            Section.Value = "{section}",
                            Or(IsBlank(Customer), Customer.Id = varCustomer.ID)
                        ),
                        "TBFeatured",
                        SortOrder.Descending
                    )"""


Y_CRUMB = f"{P.BAND} + 20"
Y_TITLE = "lblCrumbUnit.Y + lblCrumbUnit.Height + 4"
Y_SUB = "lblTitleUnit.Y + lblTitleUnit.Height"
Y_HERO = "lblSubtitleUnit.Y + lblSubtitleUnit.Height + Gutter"
Y_CFG = "cmpVersionUnit.Y + cmpVersionUnit.Height + Gutter"
Y_DOCS = ("conConfigNotesUnit.Y + "
          "If(conConfigNotesUnit.Visible, conConfigNotesUnit.Height + Gutter, 0)")
Y_FIRM = "galDocsUnit.Y + Max(galDocsUnit.Height, 40) + Gutter"

doc = f'''# Screen — Unit  (GENERATED by scripts/gen_unit.py — edit the generator)
#
# One unit inside a solution: what build it is on, what was noted about it, and its
# documents. Shares its band, version hero, config panel and document lists with
# scrSolution through scripts/screen_parts.py.
#
# varInstallation is the UNIT installation on this screen, not the solution. The back
# button restores the parent before navigating, which is the only state juggling here and
# the easiest thing to break without noticing.

Screens:
  scrUnit:
    Properties:
      Fill: =AppDark.Bg
    Children:
      - conRootUnit:
          Control: GroupContainer
          Variant: ManualLayout
          Properties:
            X: =0
            Y: =0
            Width: =Parent.Width
            Height: =Parent.Height
            Fill: =AppDark.Bg
          Children:
{P.brand_band("Unit", None, back_label="Solution", back_onselect=BACK)}

            # The trail is the only thing on this screen saying which site and which machine
            # this unit belongs to. "SDRB250" on its own could be any of them.
            - lblCrumbUnit:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter
                  Y: ={Y_CRUMB}
                  Width: ={P.CW}
                  Height: =18
                  Font: =AppFont
                  Size: =AppType.Small
                  Color: =AppDark.Muted
                  Wrap: =false
                  AutoHeight: =false
                  Text: |
                    =varCustomer.Title & "  ›  " & {PARENT_PROD}.Title

{P.title_actions("lblTitleUnit", ACTIONS)}            - lblTitleUnit:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter
                  Y: ={Y_TITLE}
                  Width: ={P.title_shrink(ACTIONS)}
                  Height: ={P.title_height()}
                  Text: ={PROD}.Title
                  Font: =AppFont
                  Size: =If(IsNarrow, AppType.Title, AppType.Display)
                  FontWeight: =FontWeight.Semibold
                  Color: =AppDark.Fg
                  Wrap: =false
                  AutoHeight: =false
            - lblSubtitleUnit:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter
                  Y: ={Y_SUB}
                  Width: ={P.CW}
                  Height: =22
                  Font: =AppFont
                  Size: =AppType.Body
                  Color: =AppDark.FgSecondary
                  Wrap: =false
                  AutoHeight: =false
                  Text: |
                    ={PROD}.'Product Type'.Value & If(varInstallation.Status.Value = "In Service", "", "  ·  " & Lower(varInstallation.Status.Value))

{P.version_hero("Unit", Y_HERO)}
{P.pencil("btnEditHeroUnit", P.admin_open("Inst", "varInstallation", False, back="scrUnit"), "Gutter + Min(" + P.CW + ", 620) - 44", f"({Y_HERO}) + 12")}

{P.config_panel("Unit", Y_CFG)}
{P.ref_gallery("Docs", "Unit", "DOCUMENTATION", "No documentation is on file for this unit.", Y_DOCS, refs("Documentation"))}
{P.ref_gallery("Firmware", "Unit", "FIRMWARE & DOWNLOADS", "No firmware or downloads are on file for this unit.", Y_FIRM, refs("Firmware & Downloads"))}
'''

OUT.write_text(doc, encoding="utf-8", newline="")
print(f"wrote {OUT}  ({len(doc.splitlines())} lines)")
