"""Generate scrEditForm.pa.yaml (and patch scrAdmin to match).

Four typed record variables - varRecCust / varRecProd / varRecInst / varRecRef -
rather than one polymorphic varAdminRecord. Power Fx infers a variable's type
from its Set() calls, and a single variable Set to records of four different
tables has no coherent type. Defaults(<table>) gives an empty record WITH a
schema, the same reason App.OnStart uses it instead of Blank().
"""
import io, sys, importlib.util, re

import os
spec = importlib.util.spec_from_file_location(
    "g", os.path.join(os.path.dirname(os.path.abspath(__file__)), "gen_admin.py"))
# gen_admin writes a file on import; re-exec just for LISTS is fine
g = importlib.util.module_from_spec(spec); spec.loader.exec_module(g)
LISTS, fid = g.LISTS, g.fid

def prop(o, k, v, ind): o.write(f"{ind}{k}: ={v}\n")
def blk(o, k, lines, ind):
    o.write(f"{ind}{k}: |\n")
    for i, l in enumerate(lines):
        o.write(f"{ind}  {'=' if i == 0 else ''}{l}\n")
def ctrl(o, name, control, ind, variant=None):
    o.write(f"{ind}- {name}:\n{ind}    Control: {control}\n")
    if variant: o.write(f"{ind}    Variant: {variant}\n")
    o.write(f"{ind}    Properties:\n")
    return ind + "      "

def var(L): return "varRec" + L["key"]

def input_name(L, f): return {"text":"txt","note":"txt","url":"txt","choice":"dd","bool":"tgl","lookup":"dd"}[f["kind"]] + fid(f) + L["key"]

# value written by Patch for one field
def patch_value(L, f):
    n, k = input_name(L, f), f["kind"]
    if k in ("text", "note", "url"): return f"{n}.Text"
    if k == "bool":                  return f"{n}.Value"
    if k == "choice":                return f"{{ Value: {n}.Selected.Value }}"
    if k == "lookup":
        # Choices() already returns records in the shape the lookup accepts.
        return f"If(IsBlank({n}.Selected), Blank(), {n}.Selected)"
    raise ValueError(k)

# Default shown in the input when editing an existing record
def default_expr(L, f):
    v, n = var(L), f["n"]
    k = f["kind"]
    if k in ("text", "note", "url"): return f'If(varAdminNew, "", {v}.{n})'
    if k == "bool":                  return f"If(varAdminNew, false, {v}.{n})"
    if k == "choice":                return f'If(varAdminNew, "", {v}.{n}.Value)'
    if k == "lookup":                return f'If(varAdminNew, "", {v}.{n}.Value)'

def default_items_expr(L, f):
    """ComboBox preselection for edit mode.

    DefaultSelectedItems takes a Table, and a SharePoint lookup projects as
    {Id, Value} -- which is not a row of the target list -- so the row has to be
    fetched back by Id rather than handed over directly.
    """
    v, n, t = var(L), f["n"], f["target"]
    return f"If(varAdminNew, Blank(), Filter({t}, ID = {v}.{n}.Id))"

def items_expr(L, f):
    if f["kind"] == "choice":
        return f"Choices({L['source']}.{f['n']})"
    if f.get("parent"):
        # Choices() gives lookup-shaped {Id, Value} records but carries no other
        # columns, so the customer scoping has to be applied by intersecting on
        # Id with the rows that qualify. IsBlank('Parent') is the runtime-verified
        # form - see app/00_Setup.md.
        # Choices() yields {Id, Value} and carries no other columns, so the
        # customer scoping is applied by asking, for each option, whether a
        # qualifying row exists. "As Opt" names the outer scope so Opt.Id is not
        # shadowed by TB_Installations' own columns in the inner Filter.
        return ("Filter(Choices(TB_Installations.'Parent') As Opt, "
                "CountRows(Filter(TB_Installations, ID = Opt.Id, "
                "Customer.Id = ddCustomerInst.Selected.Id, IsBlank('Parent'))) > 0)")
    return f"Choices({L['source']}.{f['n']})"

# ------------------------------------------------------------------ generate
o = io.StringIO()
o.write("# Generated by scripts/gen_form.py - create / edit any TB_* record.\n"
        "# Deliberately built from Classic inputs + Patch(), NOT Form + SubmitForm:\n"
        "# describe_control returns HTTP 500 for Form and DataCard, so their\n"
        "# properties cannot be verified and must not be guessed at.\n"
        "Screens:\n  scrEditForm:\n    Properties:\n      Fill: =AppTheme.Bg\n    Children:\n")
ind = "      "
p = ctrl(o, "conRootEdit", "GroupContainer", ind, "ManualLayout")
for k, v in [("Fill","AppTheme.Bg"),("Height","Parent.Height"),("Width","ContentWidth"),
             ("X","Max((Parent.Width - ContentWidth) / 2, Gutter)")]: prop(o, k, v, p)
o.write(f"{p[:-2]}Children:\n"); c = p

q = ctrl(o, "btnBackEdit", "Classic/Button", c)
for k, v in [("BorderThickness","0"),("Color","AppTheme.Primary"),("Fill","AppTheme.Bg"),
             ("Font","AppFont"),("Height","28"),("HoverColor","AppTheme.PrimaryDark"),
             ("HoverFill","AppTheme.Sunken"),
             ("OnSelect","Navigate(scrAdmin, ScreenTransition.CoverRight)"),
             ("Size","AppType.Small"),("Text",'"<  Cancel"'),("Width","Gutter * 8"),
             ("X","Gutter"),("Y","Gutter"),("FocusedBorderThickness","2"),
             ("FocusedBorderColor","AppTheme.Primary")]: prop(o, k, v, q)

q = ctrl(o, "lblTitleEdit", "Label", c)
title = ('If(varAdminNew, "New ", "Edit ") & Switch(varAdminList, '
         + ", ".join(f'"{L["key"]}", "{L["label"][:-1].lower()}"' for L in LISTS) + ', "record")')
for k, v in [("Color","AppTheme.Fg"),("Font","AppFont"),("FontWeight","FontWeight.Bold"),
             ("Height","36"),("Size","AppType.Title"),("Text",title),("Wrap","false"),
             ("AutoHeight","false"),("Width","ContentWidth - (Gutter * 2)"),
             ("X","Gutter"),("Y","Gutter + 34")]: prop(o, k, v, q)

# ---- fields, grouped per list, only the selected list visible
for L in LISTS:
    y = 120
    vis = f'varAdminList = "{L["key"]}"'
    for f in L["fields"]:
        nm, k = input_name(L, f), f["kind"]
        cap = ctrl(o, "lblCap" + fid(f) + L["key"], "Label", c)
        for kk, vv in [("Text",f'"{f["caption"]}"'),("Color","AppTheme.Muted"),
                       ("Font","AppFont"),("Size","AppType.Micro"),
                       ("FontWeight","FontWeight.Semibold"),("Wrap","false"),
                       ("AutoHeight","false"),("Height","16"),
                       ("Width","ContentWidth - (Gutter * 2)"),("X","Gutter"),
                       ("Y",str(y)),("Visible",vis)]: prop(o, kk, vv, cap)
        h = 64 if k == "note" else 40
        if k in ("text","note","url"):
            i = ctrl(o, nm, "Classic/TextInput", c)
            for kk, vv in [("Default",default_expr(L,f)),("Mode",
                            "TextMode.MultiLine" if k=="note" else "TextMode.SingleLine"),
                           ("HintText",'""'),("BorderColor","AppTheme.Line"),
                           ("BorderThickness","1"),("Color","AppTheme.Fg"),
                           ("Fill","AppTheme.Surface"),("Font","AppFont"),
                           ("Size","AppType.Body"),("Height",str(h)),
                           ("Width","ContentWidth - (Gutter * 2)"),("X","Gutter"),
                           ("Y",str(y+18)),("Visible",vis),
                           ("RadiusTopLeft","6"),("RadiusTopRight","6"),
                           ("RadiusBottomLeft","6"),("RadiusBottomRight","6")]: prop(o, kk, vv, i)
        elif k == "bool":
            i = ctrl(o, nm, "Classic/Toggle", c)
            for kk, vv in [("Default",default_expr(L,f)),("Font","AppFont"),
                           ("Size","AppType.Body"),("Height","36"),("Width","110"),
                           ("X","Gutter"),("Y",str(y+18)),("Visible",vis),
                           ("TrueFill","AppTheme.Ok"),("FalseFill","AppTheme.Faint")]: prop(o, kk, vv, i)
            h = 36
        elif k == "choice":
            i = ctrl(o, nm, "Classic/DropDown", c)
            o.write(f"{i}Items: |\n{i}  ={items_expr(L,f)}\n")
            for kk, vv in [("Default",default_expr(L,f)),
                           ("AllowEmptySelection","true"),
                           ("BorderColor","AppTheme.Line"),("BorderThickness","1"),
                           ("Color","AppTheme.Fg"),("Fill","AppTheme.Surface"),
                           ("Font","AppFont"),("Size","AppType.Body"),("Height","40"),
                           ("Width","ContentWidth - (Gutter * 2)"),("X","Gutter"),
                           ("Y",str(y+18)),("Visible",vis)]: prop(o, kk, vv, i)
        else:
            # Lookups use a Drop down with an explicit Value column.
            #
            # Per the Drop down control reference: "Items - The source of data
            # that contains the items that appear in the control. If the source
            # has multiple columns, set the control's Value property to the
            # column of data that you want to show." A SharePoint list is always
            # multi-column, so without Value the control has no display column
            # and renders an empty list.
            #
            # Note describe_control does not return Value among Classic/DropDown's
            # input properties, though the documentation lists it as a key one.
            #
            # ComboBox was tried and abandoned: Studio seeds it with a SearchItems
            # default of Search(ComboBoxSample, ..., "Value1"), a sample source
            # that does not exist here, and that property cannot be overridden
            # from YAML ("Unknown property 'SearchItems'"). IsSearchable: =false
            # does not stop it being evaluated either.
            i = ctrl(o, nm, "Classic/DropDown", c)
            o.write(f"{i}Items: |\n{i}  ={items_expr(L,f)}\n")
            for kk, vv in [("Default",default_expr(L,f)),
                           ("AllowEmptySelection","true"),
                           ("BorderColor","AppTheme.Line"),("BorderThickness","1"),
                           ("Color","AppTheme.Fg"),("Fill","AppTheme.Surface"),
                           ("Font","AppFont"),("Size","AppType.Body"),("Height","40"),
                           ("Width","ContentWidth - (Gutter * 2)"),("X","Gutter"),
                           ("Y",str(y+18)),("Visible",vis)]: prop(o, kk, vv, i)
        y += 18 + h + 14

# ---- save
q = ctrl(o, "btnSaveEdit", "Classic/Button", c)
lines = ["IfError("]
for idx, L in enumerate(LISTS):
    # each assignment must be its own entry: blk() prefixes per line, so a
    # multi-line string here would leave later lines under-indented and
    # silently terminate the YAML block scalar.
    fl = [f"                {f['n']}: {patch_value(L, f)}" for f in L["fields"]]
    fl = [x + ("," if i < len(fl) - 1 else "") for i, x in enumerate(fl)]
    lines += [f'    If(varAdminList = "{L["key"]}",',
              f"        Patch({L['source']},",
              f"            If(varAdminNew, Defaults({L['source']}), {var(L)}),",
              "            {"] + fl + [
              "            }",
              "        )",
              "    );"]
lines += ['    Set(varEditError, "");',
          "    Navigate(scrAdmin, ScreenTransition.UnCoverRight),",
          "    Set(varEditError, FirstError.Message)",
          ")"]
blk(o, "OnSelect", lines, q)
for k, v in [("Font","AppFont"),("Size","AppType.Body"),("FontWeight","FontWeight.Semibold"),
             ("Text",'"Save"'),("Fill","AppTheme.Primary"),("Color","AppTheme.OnPrimary"),
             ("HoverFill","AppTheme.PrimaryDark"),("BorderThickness","0"),
             ("Height","44"),("Width","160"),("X","Gutter"),
             ("Y","Parent.Height - Gutter - 44"),
             ("RadiusTopLeft","6"),("RadiusTopRight","6"),
             ("RadiusBottomLeft","6"),("RadiusBottomRight","6"),
             ("FocusedBorderThickness","2"),("FocusedBorderColor","AppTheme.Primary")]: prop(o, k, v, q)

q = ctrl(o, "lblEditError", "Label", c)
# AppTheme on this branch has Warn / WarnLight but no Danger slot, so the
# save-failure message uses an explicit error red rather than an amber.
for k, v in [("Text","varEditError"),("Color","RGBA(176, 0, 32, 1)"),("Font","AppFont"),
             ("Size","AppType.Small"),("Wrap","true"),("AutoHeight","false"),
             ("Height","44"),("Width","ContentWidth - (Gutter * 2) - 176"),
             ("X","Gutter + 176"),("Y","Parent.Height - Gutter - 44"),
             ("Visible","!IsBlank(varEditError)")]: prop(o, k, v, q)

open(r"E:\Papp\tt2\scrEditForm.pa.yaml", "w", encoding="utf-8", newline="").write(o.getvalue())
print("wrote scrEditForm.pa.yaml")
