"""Generate scrOnboard.pa.yaml - the new-customer wizard.

One screen. The customer form is the whole screen until the customer exists;
rather than holding everything until the end:

  1  customer  -> Patch TB_Customers, keep the created record in varWizCust
  2  solutions -> Patch TB_Installations with Parent blank
  3  units     -> Patch TB_Installations with Parent set to a step-2 solution

Writing at each step is deliberate. Steps 2 and 3 need real rows: step 3's
solution picker is a Choices() dropdown scoped to rows that must already exist,
and Patch needs a real Customer Id. Holding it all in memory would also lose
everything on a refresh. The cost is that abandoning midway leaves a customer
with no equipment, and there is no delete to clean that up.

Installation titles are composed as "<customer> - <product>", matching the
seed convention (e.g. "Northgate Retail Group - CI 300X"), so there is no
title to type.

Controls follow the same rules as the admin form: no Form/DataCard (their
properties cannot be verified), and lookup dropdowns use Choices() because
Classic/DropDown.Value is rejected by the compiler. See app/00_Setup.md.
"""

import screen_parts as P
import io

def prop(o, k, v, ind):
    # A Power Fx value containing ": " terminates the YAML key when written
    # inline, and the parse error then surfaces hundreds of lines away as
    # "mapping values are not allowed here". Emit those as block scalars.
    # See scripts/testdata/bad_inline_colon.pa.yaml.
    if ": " in v:
        o.write(f"{ind}{k}: |\n{ind}  ={v}\n")
    else:
        o.write(f"{ind}{k}: ={v}\n")
def blk(o, k, lines, ind):
    o.write(f"{ind}{k}: |\n")
    for i, l in enumerate(lines):
        o.write(f"{ind}  {'=' if i == 0 else ''}{l}\n")
def ctrl(o, name, control, ind, variant=None):
    o.write(f"{ind}- {name}:\n{ind}    Control: {control}\n")
    if variant: o.write(f"{ind}    Variant: {variant}\n")
    o.write(f"{ind}    Properties:\n")
    return ind + "      "

# Radius is supported only on Classic/Button and Classic/TextInput -- a
# Classic/DropDown rejects it outright. See app/00_Setup.md.
FIELD = [("BorderColor","AppDark.Line"),("BorderThickness","1"),
         ("Color","AppDark.Fg"),("Fill","AppDark.Surface"),
         ("Font","AppFont"),("Size","AppType.Body")]
RADIUS = [("RadiusTopLeft","6"),("RadiusTopRight","6"),
          ("RadiusBottomLeft","6"),("RadiusBottomRight","6")]
BTN = [("Font","AppFont"),("Size","AppType.Body"),
       ("FontWeight","FontWeight.Semibold"),("BorderThickness","0"),
       ("Color","AppDark.OnBrand"),("Height","44"),
       ("RadiusTopLeft","6"),("RadiusTopRight","6"),
       ("RadiusBottomLeft","6"),("RadiusBottomRight","6"),
       ("FocusedBorderThickness","2"),("FocusedBorderColor","AppDark.Accent")]

o = io.StringIO()
o.write(__doc__.split("\n\n")[0].replace("Generate ", "# ") + "\n")
o.write("# Generated by scripts/gen_onboard.py - do not hand-edit.\n")
# The wizard owns its step counter, so it resets it here rather than trusting
# whoever navigated in. It used to rely on the calling button doing
# Set(varWizStep, 1); when that button was rewritten the Set was lost, and every
# step-1 control - all of which test varWizStep = 1 - silently vanished, leaving
# an empty screen. Screen-internal state belongs in OnVisible. Only genuine
# parameters, like varCustomer or varAdminNew, should arrive from the caller.
o.write('Screens:\n  scrOnboard:\n    Properties:\n      Fill: =AppDark.Bg\n'
        '      OnVisible: |\n'
        '        =Set(varWizCust, Blank());\n'
        '        Set(varWizError, "")\n'
        '    Children:\n')
ind = "      "
p = ctrl(o, "conRootWiz", "GroupContainer", ind, "ManualLayout")
for k, v in [("Fill","AppDark.Bg"),("Height","Parent.Height"),
             ("Width","ContentWidth"),
             ("X","Max((Parent.Width - ContentWidth) / 2, Gutter)")]: prop(o, k, v, p)
o.write(f"{p[:-2]}Children:\n"); c = p
o.write(P.brand_band("Wiz", "scrAdmin", back_transition="UnCoverRight", back_label="Admin") + "\n")

# ---- chrome -------------------------------------------------------------
q = ctrl(o, "btnWizCancel", "Classic/Button", c)
for k, v in [("BorderThickness","0"),("Color","AppDark.Accent"),
             ("Fill","AppDark.Bg"),("Font","AppFont"),("Height","44"),
             ("HoverColor","AppDark.AccentSolid"),("HoverFill","AppDark.Sunken"),
             ("OnSelect","Navigate(scrHome, ScreenTransition.CoverRight)"),
             ("Size","AppType.Small"),("Text",'"<  Home"'),("Width","Gutter * 8"),
             ("X","Gutter"),("Y","56 + 12"),("FocusedBorderThickness","2"),
             ("FocusedBorderColor","AppDark.Accent")]: prop(o, k, v, q)

q = ctrl(o, "lblWizTitle", "Label", c)
for k, v in [("Color","AppDark.Fg"),("Font","AppFont"),
             ("FontWeight","FontWeight.Bold"),("Height","36"),
             ("Size","AppType.Title"),("Wrap","false"),("AutoHeight","false"),
             ("Text",'"New customer"'),
             ("Width","ContentWidth - (Gutter * 2)"),("X","Gutter"),
             # Stacked under the Home button (68..112), with the fields from 172. All three
             # used to sit in the same 80..150 band: Home 80..124, title 114..150 and the
             # first caption at 112, so the wizard opened with its first field unlabelled
             # and its title struck through by a button.
             ("Y","120")]: prop(o, k, v, q)

q = ctrl(o, "lblWizStep", "Label", c)
steps = '"Create the site, then add the machines on it."'
for k, v in [("Color","AppDark.Muted"),("Font","AppFont"),
             ("Size","AppType.Small"),("FontWeight","FontWeight.Semibold"),
             ("Height","20"),("Wrap","false"),("AutoHeight","false"),
             ("Text",steps),("Width","ContentWidth - (Gutter * 2)"),
             # Directly under the title (120..156), with the fields from 188.
             ("X","Gutter"),("Y","158")]: prop(o, k, v, q)

def caption(name, text, y, vis):
    q = ctrl(o, name, "Label", c)
    for k, v in [("Text",f'"{text}"'),("Color","AppDark.Muted"),
                 ("Font","AppFont"),("Size","AppType.Small"),
                 ("FontWeight","FontWeight.Semibold"),("Wrap","false"),
                 ("AutoHeight","false"),("Height","18"),
                 ("Width","ContentWidth - (Gutter * 2)"),("X","Gutter"),
                 ("Y",str(y)),("Visible",vis)]: prop(o, k, v, q)

def textin(name, y, vis, multiline=False, default='""'):
    h = 64 if multiline else 40
    q = ctrl(o, name, "Classic/TextInput", c)
    for k, v in [("Default",default),
                 ("Mode","TextMode.MultiLine" if multiline else "TextMode.SingleLine"),
                 ("HintText",'""'),("Height",str(h)),
                 ("Width","ContentWidth - (Gutter * 2)"),("X","Gutter"),
                 ("Y",str(y)),("Visible",vis)] + FIELD + RADIUS: prop(o, k, v, q)
    return h

def dropdown(name, items, y, vis, onchange=None, width=None,
             display="ThisItem.Value"):
    """ModernDropdown. ItemDisplayText names the column to show - the
    property Classic/DropDown lacked, and the reason a multi-column Items
    rendered blank and had to be reduced with ShowColumns. Selected returns
    the whole record now, so the row behind a choice is reachable directly."""
    q = ctrl(o, name, "ModernDropdown", c)
    o.write(f"{q}Items: |\n{q}  ={items}\n")
    if onchange: blk(o, "OnChange", onchange, q)
    for k, v in [("ItemDisplayText",display),
                 ("Height","40"),("Width",width or "ContentWidth - (Gutter * 2)"),
                 ("X","Gutter"),("Y",str(y)),("Visible",vis)] + FIELD: prop(o, k, v, q)

ODATA = "'@odata.type': \"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\","

def spref(indent, idexpr, valexpr, tail=","):
    """The literal record shape a SharePoint lookup column accepts.

    Choices() is the documented way to fill a lookup *dropdown*, but its result
    is a cached snapshot of the target list taken when the app loaded. A
    customer created moments earlier in this same wizard is not in it, so
    LookUp(Choices(...), Id = varWizCust.ID) returns blank -- and Customer is a
    required column, so the Patch fails and nothing is written at all.
    Building the reference by hand from a record we already hold sidesteps the
    cache entirely. This is what scripts/gen_form.py does.
    """
    return [f"{indent}{{ {ODATA}",
            f"{indent}  Id: {idexpr}, Value: {valexpr} }}{tail}"]

def hint(name, text, y, vis):
    q = ctrl(o, name, "Label", c)
    for k, v in [("Text",text),("Color","AppDark.Muted"),("Font","AppFont"),
                 ("Size","AppType.Small"),("Wrap","false"),("AutoHeight","false"),
                 ("Height","18"),("Width","ContentWidth - (Gutter * 2)"),
                 ("X","Gutter"),("Y",str(y)),("Visible",vis)]: prop(o, k, v, q)

def standard_hint(dd):
    """"Standard for CI 300X is K38" - what the catalogue says should be there."""
    return ('If(IsBlank(' + dd + '.Selected), '
            '"The software build running on the machine, not the model number.", '
            '"Standard for " & ' + dd + '.Selected.Value & " is " & '
            'Coalesce(LookUp(TB_Products, ID = ' + dd + ".Selected.Id, "
            '\'Current Standard Version\'), "not recorded"))')

# ---- step 1: the customer ----------------------------------------------
# The customer form IS the screen until the customer exists. varWizCust is set
# by the Patch that creates it, so no step counter is needed to know.
MADE = "!IsBlank(varWizCust)"
V1 = f"!({MADE})"
y = 188
for nm, cap, ml in [("txtWizCustName","Customer name",False),
                    ("txtWizCustDesc","Description",True),
                    ("txtWizCustNotes","Support notes",True)]:
    caption("lblCap" + nm[6:], cap, y, V1)
    y += 18 + textin(nm, y + 18, V1, ml) + 14

caption("lblCapWizCustActive", "Active", y, V1)
q = ctrl(o, "tglWizCustActive", "ModernToggle", c)
for k, v in [("Default","true"),("Font","AppFont"),("Size","AppType.Body"),
             ("Height","36"),("Width","110"),("X","Gutter"),("Y",str(y+18)),
             ("Visible",V1)]: prop(o, k, v, q)

q = ctrl(o, "btnWizStep1Next", "Classic/Button", c)
blk(o, "OnSelect", [
    "IfError(",
    "    Set(varWizCust,",
    "        Patch(TB_Customers, Defaults(TB_Customers),",
    "            {",
    "                Title: txtWizCustName.Text,",
    "                Description: txtWizCustDesc.Text,",
    "                'Support Notes': txtWizCustNotes.Text,",
    "                Active: tglWizCustActive.Checked",
    "            }",
    "        )",
    "    );",
    '    Set(varWizError, "");',
    '    Set(varWizError, ""),',
    "    Set(varWizError, FirstError.Message)",
    ")"], q)
for k, v in [("Text",'"Create customer"'),("Fill","AppDark.Accent"),
             ("HoverFill","AppDark.AccentSolid"),("Width","210"),
             ("X","Gutter"),("Y","Parent.Height - Gutter - 44"),
             ("Visible",f"{V1} && Len(Trim(txtWizCustName.Text)) > 0")] + BTN:
    prop(o, k, v, q)

# ---- step 2: solutions --------------------------------------------------
V2 = MADE
y = 188
# Once the customer exists the form above collapses to this line, and the machines
# section takes the rest of the screen.
q = ctrl(o, "lblWizMadeCust", "Label", c)
for k, v in [("Text",'"\u2713  " & varWizCust.Title'),("Color","AppDark.Ok"),
             ("Font","AppFont"),("Size","AppType.Body"),
             ("FontWeight","FontWeight.Semibold"),("Wrap","false"),
             ("AutoHeight","false"),("Height","24"),
             ("Width","ContentWidth - (Gutter * 2)"),("X","Gutter"),
             ("Y","188"),("Visible",V2)]: prop(o, k, v, q)

# Narrow deliberately: the count sits beside it, and caption() spans the full measure.
q = ctrl(o, "lblCapWizMachines", "Label", c)
for k, v in [("Text",'"MACHINES ON SITE"'),("Color","AppDark.Muted"),
             ("Font","AppFont"),("Size","AppType.Small"),
             ("FontWeight","FontWeight.Bold"),("Wrap","false"),
             ("AutoHeight","false"),("Height","18"),("Width","200"),
             ("X","Gutter"),("Y","224"),("Visible",V2)]: prop(o, k, v, q)

# Adding one opens the real form, seeded with this customer - the same route, and the same
# COMES WITH panel, an admin gets from the customer's own page. It returns here.
o.write(P.admin_button(
    "btnWizAddMachine", "+  Add a machine",
    P.admin_open("Inst", "Defaults(TB_Installations)", True, back="scrOnboard",
                 extra=P.stash([("varStCustomerInst", "varWizCust")])),
    x="Gutter", y="Parent.Height - Gutter - 44", width="ContentWidth - (Gutter * 2) - 180",
    height=44, ind=12, visible=V2))

y = 248
q = ctrl(o, "galWizSolutions", "Gallery", c, "Vertical")
o.write(f"{q}Items: |\n{q}  =Filter(TB_Installations, "
        f"Customer.Id = varWizCust.ID, IsBlank('Parent'))\n")
for k, v in [("Visible",V2),("X","Gutter"),("Y",str(y)),
             ("Width","ContentWidth - (Gutter * 2)"),
             ("Height",f"Max(Parent.Height - {y} - Gutter - 60, 120)"),
             ("TemplateSize","48"),("TemplatePadding","4"),
             ("ShowScrollbar","true")]: prop(o, k, v, q)
o.write(f"{q[:-2]}Children:\n")
r = ctrl(o, "lblWizSolRow", "Label", q)
o.write(f'{r}Text: |\n{r}  =ThisItem.Title & "   " '
        f'& CountRows(Filter(TB_Installations, \'Parent\'.Id = ThisItem.ID)) '
        f'& " unit(s)"\n')
for k, v in [("Color","AppDark.Fg"),("Font","AppFont"),("Size","AppType.Small"),
             ("Wrap","false"),("AutoHeight","false"),("PaddingLeft","10"),
             ("Fill","AppDark.Sunken"),("X","0"),("Y","0"),
             ("Width","Parent.TemplateWidth"),("Height","36")]: prop(o, k, v, r)

q = ctrl(o, "lblWizSolCount", "Label", c)
SOLN = ("CountRows(Filter(TB_Installations, Customer.Id = varWizCust.ID, "
        "IsBlank('Parent')))")
solcount = (f'If({SOLN} = 0, "No machines added yet.", '
            f'{SOLN} = 1, "1 machine added.", '
            f'{SOLN} & " machines added.")')
for k, v in [("Text",solcount),("Color","AppDark.Muted"),("Font","AppFont"),
             ("Size","AppType.Small"),("FontWeight","FontWeight.Semibold"),
             ("Wrap","false"),("AutoHeight","false"),("Height","20"),
             ("Width","360"),("X","Gutter + 220"),("Y","224"),
             ("Visible",V2)]: prop(o, k, v, q)

q = ctrl(o, "btnWizFinish", "Classic/Button", c)
blk(o, "OnSelect", [
    "Set(varCustomer, varWizCust);",
    "Navigate(scrCustomerOverview, ScreenTransition.Cover)"], q)
for k, v in [("Text",'"Done"'),("Fill","AppDark.Accent"),
             ("HoverFill","AppDark.AccentSolid"),("Width","190"),
             ("X","ContentWidth - Gutter - 190"),
             ("Y","Parent.Height - Gutter - 44"),("Visible",V2)] + BTN:
    prop(o, k, v, q)

# ---- error line ---------------------------------------------------------
q = ctrl(o, "lblWizError", "Label", c)
for k, v in [("Text","varWizError"),("Color","AppDark.Danger"),
             ("Font","AppFont"),("Size","AppType.Small"),("Wrap","true"),
             ("AutoHeight","false"),("Height","44"),
             ("Width","ContentWidth - (Gutter * 2) - 420"),
             ("X","Gutter + 220"),("Y","Parent.Height - Gutter - 44"),
             ("Visible","!IsBlank(varWizError)")]: prop(o, k, v, q)


# The generators emit classic controls; modernize.py owns the single mapping to
# their Fluent equivalents, so regenerating never silently reverts a screen.
import importlib.util as _ilu, os as _os
_spec = _ilu.spec_from_file_location(
    "modernize", _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), "modernize.py"))
_mz = _ilu.module_from_spec(_spec); _spec.loader.exec_module(_mz)

def _modern(src):
    src, rep = _mz.modernize_source(src)
    for line in rep:
        print(line)
    return src


open(r"E:\Papp\powerappgoofing\app\screens\scrOnboard.pa.yaml", "w", encoding="utf-8", newline="").write(_modern(o.getvalue()))
print("wrote scrOnboard.pa.yaml")
