"""Generate scrSolution: the machine detail screen, rebuilt dark.

WHAT WAS WRONG WITH IT

Three things, all structural rather than cosmetic:

1. THE ANSWER WAS NOT THE HEADLINE. "Is this on the current build?" was three 22pt labels
   and a small badge, sitting below a title and a subtitle. Now it is a chamfered hero panel
   with a state-coloured rail, carrying the comparison at Display size - the largest thing on
   the screen, because it is the reason the screen exists.

2. UNIT ROWS WERE PROSE. One concatenated string per row:
       NOTE RECYCLER   SDRB250   3.4.1  ·  standard 3.6.0
   A technician scanning six units read six sentences. Now each row is a status rail, a
   category, a model, and a right-aligned comparison - so the eye runs down one column and
   the mismatches stand out without reading.

3. EVERY Y WAS A HAND-COPIED ARITHMETIC CHAIN. The old file repeated
   "Gutter + 100 + 112 + Gutter + 92 + Gutter + 32 + 160 + Gutter + 32" in full, in six
   controls, each an independent chance to be a pixel out. Positions here chain through
   control references (thing.Y + thing.Height + gap) so each offset has exactly one author.
   The conditional config panel is handled by If(Visible, Height + Gutter, 0) rather than by
   branching the whole chain, which is what forced the copying before.

WHY THE ROW STATUS IS NOT THE COMPONENT

cmpVersionChip cannot go here: "You can't insert a component into a gallery or a form." The
component is used once on this screen, for the hero panel, which is outside any gallery. Row
status is built from controls, so the four-state logic exists twice in this app - once in the
component, once below. They must be changed together.

BEHAVIOUR IS UNCHANGED. Same filters, same navigation, same retired-row exclusions, same
customer-specific document exceptions.
"""
from pathlib import Path
import screen_parts as P

OUT = Path(r"E:\Papp\powerappgoofing\app\screens\scrSolution.pa.yaml")

BAND = P.BAND
CW = P.CW

# The product this installation is an instance of, and its catalogue standard.
PROD = "LookUp(TB_Products, ID = varInstallation.Product.Id)"

# The installation of a unit row's model under this solution, if one exists. Repeated
# rather than named because this environment has no With/As available inside a gallery row.
FITTED = ("LookUp(TB_Installations, 'Parent'.Id = varInstallation.ID "
          "&& Product.Id = ThisItem.Unit.Id)")
UPROD = "LookUp(TB_Products, ID = ThisItem.Unit.Id)"

# Units attached here that the model does not list. Rare, but silently hiding one would be
# this app's characteristic failure: a correct-looking screen missing a machine.
STRAY = ("CountRows(Filter(TB_Installations As I, I.'Parent'.Id = varInstallation.ID, "
         "I.Status.Value <> \"Retired\", "
         "CountRows(Filter(TB_SolutionUnits, Solution.Id = varInstallation.Product.Id, "
         "Unit.Id = I.Product.Id)) = 0))")


def refs(section):
    """Documents or firmware for this machine OR any unit actually fitted under it.

    "As R" names the outer row so R.Product.Id is not shadowed by TB_Installations' own
    Product column in the nested Filter.
    """
    return f"""=SortByColumns(
                        Filter(
                            TB_References As R,
                            R.Section.Value = "{section}",
                            Or(IsBlank(R.Customer), R.Customer.Id = varCustomer.ID),
                            R.Product.Id = varInstallation.Product.Id
                            || CountRows(
                                   Filter(
                                       TB_Installations,
                                       'Parent'.Id = varInstallation.ID,
                                       Status.Value <> "Retired",
                                       Product.Id = R.Product.Id
                                   )
                               ) > 0
                        ),
                        "TBFeatured",
                        SortOrder.Descending
                    )"""


# Vertical chain. Each offset has exactly one author; the config panel contributes its
# height only when it is visible, so nothing downstream needs a branch of its own.
Y_TITLE = f"{BAND} + 24"
Y_SUB = "lblTitleSol.Y + lblTitleSol.Height"
Y_HERO = "lblSubtitleSol.Y + lblSubtitleSol.Height + Gutter"
Y_CFG = "cmpVersionSol.Y + cmpVersionSol.Height + Gutter"
Y_UNITS = "conConfigNotesSol.Y + If(conConfigNotesSol.Visible, conConfigNotesSol.Height + Gutter, 0)"
Y_DOCS = "galUnitsSol.Y + galUnitsSol.Height + Gutter"
Y_FIRM = "galDocsSol.Y + Max(galDocsSol.Height, 40) + Gutter"

doc = f'''# Screen — Solution  (GENERATED by scripts/gen_solution.py — edit the generator)
#
# The machine detail screen. See the generator docstring for what was rebuilt and why: the
# version answer is now the headline rather than a footnote, unit rows are scannable columns
# rather than sentences, and vertical positions chain through control references instead of
# repeating a hand-copied arithmetic sum in six places.
#
# varInstallation is the solution installation; varCustomer is the site. Both are set by
# whoever navigated here and are never re-derived on this screen.

Screens:
  scrSolution:
    Properties:
      Fill: =AppDark.Bg
    Children:
      - conRootSol:
          Control: GroupContainer
          Variant: ManualLayout
          Properties:
            X: =0
            Y: =0
            Width: =Parent.Width
            Height: =Parent.Height
            Fill: =AppDark.Bg
          Children:
{P.brand_band("Sol", "scrCustomerOverview")}

            - lblTitleSol:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter
                  Y: ={Y_TITLE}
                  Width: ={CW}
                  Height: =41
                  Text: ={PROD}.Title
                  Font: =AppFont
                  Size: =If(IsNarrow, AppType.Title, AppType.Display)
                  FontWeight: =FontWeight.Semibold
                  Color: =AppDark.Fg
                  Wrap: =false
                  AutoHeight: =false
            - lblSubtitleSol:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter
                  Y: ={Y_SUB}
                  Width: ={CW}
                  Height: =22
                  Font: =AppFont
                  Size: =AppType.Body
                  Color: =AppDark.FgSecondary
                  Wrap: =false
                  AutoHeight: =false
                  Text: |
                    ={PROD}.Family.Value & "  ·  " & varCustomer.Title & If(varInstallation.Status.Value = "In Service", "", "  ·  " & Lower(varInstallation.Status.Value))

{P.version_hero("Sol", Y_HERO, PROD)}

{P.config_panel("Sol", Y_CFG)}

            # ---- units
            # A row is a unit the MODEL takes, so it may have nothing behind it. That is the
            # point: "do they have a barcode scanner" was unanswerable when the list only
            # showed what happened to be attached, because absent and uncatalogued looked
            # identical.
            - lblUnitsHeading:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter
                  Y: |
                    ={Y_UNITS}
                  Width: ={CW}
                  Height: =22
                  Font: =AppFont
                  Size: =AppType.Small
                  FontWeight: =FontWeight.Bold
                  Color: =AppDark.Muted
                  Wrap: =false
                  AutoHeight: =false
                  Text: |
                    ="UNITS" & If({STRAY} > 0, "   (" & {STRAY} & " also attached, not on the model's list)", "")
            - galUnitsSol:
                Control: Gallery
                Variant: Vertical
                Properties:
                  X: =Gutter
                  Y: =lblUnitsHeading.Y + lblUnitsHeading.Height + 10
                  Width: ={CW}
                  Height: =Max(Min(CountRows(galUnitsSol.AllItems), 5), 1) * 56
                  TemplateSize: =56
                  TemplatePadding: =0
                  ShowScrollbar: =false
                  Items: |
                    =Sort(
                        Filter(TB_SolutionUnits, Solution.Id = varInstallation.Product.Id),
                        Unit.Value,
                        SortOrder.Ascending
                    )
                Children:
                  # The rail is the whole point of the row. Four states, same order and same
                  # meaning as the component - change both together.
                  - recUnitRailSol:
                      Control: Rectangle
                      Properties:
                        OnSelect: =Select(Parent)
                        X: =0
                        Y: =0
                        Width: =3
                        Height: =Parent.TemplateHeight - 1
                        Fill: |
                          =If(
                              IsBlank({FITTED}),
                              AppDark.Line,
                              IsBlank({FITTED}.'Installed Version'),
                              AppDark.Muted,
                              IsBlank({UPROD}.'Current Standard Version'),
                              AppDark.Muted,
                              {FITTED}.'Installed Version' = {UPROD}.'Current Standard Version',
                              AppDark.Ok,
                              AppDark.Warn
                          )
                  - lblUnitTypeSol:
                      Control: ModernText
                      Properties:
                        PaddingTop: =0
                        PaddingBottom: =0
                        OnSelect: =Select(Parent)
                        X: =16
                        Y: =8
                        Width: =(Parent.TemplateWidth - 32) * 0.55
                        Height: =18
                        Text: =Upper({UPROD}.'Product Type'.Value)
                        Font: =AppFont
                        Size: =AppType.Small
                        FontWeight: =FontWeight.Semibold
                        Color: =AppDark.Muted
                        Wrap: =false
                        AutoHeight: =false
                  - lblUnitModelSol:
                      Control: ModernText
                      Properties:
                        PaddingTop: =0
                        PaddingBottom: =0
                        OnSelect: =Select(Parent)
                        X: =16
                        Y: =27
                        Width: =(Parent.TemplateWidth - 32) * 0.55
                        Height: =22
                        Text: =ThisItem.Unit.Value
                        Font: =AppFont
                        Size: =AppType.Body
                        FontWeight: =FontWeight.Semibold
                        Color: =If(IsBlank({FITTED}), AppDark.Faint, AppDark.Fg)
                        Wrap: =false
                        AutoHeight: =false
                  # Right-aligned so the versions form one column down the list. A mismatch
                  # then shows as a break in the column rather than as a sentence to read.
                  - lblUnitVerSol:
                      Control: ModernText
                      Properties:
                        PaddingTop: =0
                        PaddingBottom: =0
                        OnSelect: =Select(Parent)
                        X: =16 + ((Parent.TemplateWidth - 32) * 0.55)
                        Y: =17
                        Width: =(Parent.TemplateWidth - 32) * 0.45
                        Height: =22
                        Align: =Align.Right
                        Font: =AppFont
                        Size: =AppType.Body
                        FontWeight: =FontWeight.Semibold
                        Wrap: =false
                        AutoHeight: =false
                        Text: |
                          =If(
                              IsBlank({FITTED}),
                              "not recorded",
                              IsBlank({FITTED}.'Installed Version'),
                              "version not recorded",
                              IsBlank({UPROD}.'Current Standard Version'),
                              {FITTED}.'Installed Version',
                              {FITTED}.'Installed Version' = {UPROD}.'Current Standard Version',
                              {FITTED}.'Installed Version',
                              {FITTED}.'Installed Version' & "  →  " & {UPROD}.'Current Standard Version'
                          )
                        Color: |
                          =If(
                              IsBlank({FITTED}),
                              AppDark.Faint,
                              IsBlank({FITTED}.'Installed Version'),
                              AppDark.Muted,
                              IsBlank({UPROD}.'Current Standard Version'),
                              AppDark.Muted,
                              {FITTED}.'Installed Version' = {UPROD}.'Current Standard Version',
                              AppDark.Ok,
                              AppDark.Warn
                          )
                  - recUnitRuleSol:
                      Control: Rectangle
                      Properties:
                        OnSelect: =Select(Parent)
                        X: =0
                        Y: =55
                        Width: =Parent.TemplateWidth
                        Height: =1
                        Fill: =AppDark.Line
                  - galUnitsHitSol:
                      Control: Classic/Button
                      Properties:
                        X: =0
                        Y: =0
                        Width: =Parent.TemplateWidth
                        Height: =Parent.TemplateHeight
                        Text: =""
                        Fill: =RGBA(0, 0, 0, 0)
                        HoverFill: =RGBA(255, 255, 255, 0.06)
                        PressedFill: =RGBA(106, 115, 230, 0.18)
                        BorderThickness: =0
                        HoverBorderColor: =RGBA(0, 0, 0, 0)
                        PressedBorderColor: =RGBA(0, 0, 0, 0)
                        FocusedBorderThickness: =2
                        FocusedBorderColor: =AppDark.Accent
                        OnSelect: |
                          =If(
                              !IsBlank({FITTED}),
                              Set(varInstallation, {FITTED});
                              Navigate(scrUnit, ScreenTransition.Cover)
                          )
            - lblNoUnits:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter
                  Y: =galUnitsSol.Y
                  Width: ={CW}
                  Height: =40
                  Text: ="No units are on file for this model. Add them under Admin, Solution units."
                  Font: =AppFont
                  Size: =AppType.Body
                  Color: =AppDark.Muted
                  Visible: =CountRows(Filter(TB_SolutionUnits, Solution.Id = varInstallation.Product.Id)) = 0
{P.ref_gallery("Docs", "Sol", "DOCUMENTATION", "No documentation is on file for this system.", Y_DOCS, refs("Documentation"))}
{P.ref_gallery("Firmware", "Sol", "FIRMWARE & DOWNLOADS", "No firmware or downloads are on file for this system.", Y_FIRM, refs("Firmware & Downloads"))}
'''

OUT.write_text(doc, encoding="utf-8", newline="")
print(f"wrote {OUT}  ({len(doc.splitlines())} lines)")
