"""Generate scrCustomers: the site list, rebuilt dark.

WHAT IT GAINS: A REASON TO SCAN IT

Rows were a name and a description. That answers "which site" and nothing else, so the only
way to learn whether a site needed attention was to open it. Each row now carries a count of
machines behind their standard, which is the question a technician is usually holding when
they open this list.

WHY IT NEVER SAYS "ALL GOOD"

The row warns when something is behind and stays quiet otherwise. It deliberately does NOT
render a green "up to date" state, because this data cannot support that claim: a site whose
installed versions were never surveyed looks identical to one that is genuinely current, and
a green tick over unsurveyed machines is worse than no tick at all. Silence means "nothing
known to be wrong", which is what is actually true.

That choice also halves the work per row - see below.

COST PER ROW

The behind-count is a Filter with a nested LookUp per installation, which SharePoint cannot
delegate; it runs client-side against the row limit. That is one such count per customer
rendered, plus one cheap solution count. Acceptable for a branch list in the tens, and worth
watching if TB_Customers grows into the hundreds - the fix then is a rollup column
maintained by the wizard rather than a per-row scan here.

Units carry Customer as well as Parent (confirmed in the seed data and in gen_onboard's
child Patch), so one filter on Customer.Id sees every machine at a site without walking the
parent chain.
"""
from pathlib import Path
import screen_parts as P

OUT = Path(r"E:\Papp\powerappgoofing\app\screens\scrCustomers.pa.yaml")

CARD_H = 76

# Machines at this site whose installed version differs from their product's standard.
# Rows with no version, or a product with no standard, are not "behind" - they are unknown,
# and the three-state distinction is the whole point of this app.
# The version in force for a machine: its own, else the site baseline for that
# model. Written out twice below because a gallery row has no local name to bind it to, and
# it must match screen_parts.effective_version exactly - the hero and this count disagreeing
# is precisely the bug this replaced.
_EFF = ("Coalesce(I.'Installed Version', "
        "LookUp(TB_SoftwareVersions, Customer.Id = ThisItem.ID && Product.Id = I.Product.Id).Version)")

BEHIND = ("CountRows(Filter(TB_Installations As I, I.Customer.Id = ThisItem.ID, "
          "I.Status.Value <> \"Retired\", "
          f"!IsBlank({_EFF}), "
          "!IsBlank(LookUp(TB_Products, ID = I.Product.Id).'Current Standard Version'), "
          f"{_EFF} <> LookUp(TB_Products, ID = I.Product.Id)"
          ".'Current Standard Version'))")

# Solutions only: installations with no Parent. Cheap, and the number a technician thinks in.
SOL_N = ("CountRows(Filter(TB_Installations, Customer.Id = ThisItem.ID, "
         "IsBlank(ThisRecord.'Parent'), Status.Value <> \"Retired\"))")

doc = f'''# Screen — Customers  (GENERATED by scripts/gen_customers.py — edit the generator)
#
# The site list. Rows warn when a site has machines behind their standard and stay quiet
# otherwise - never a green "all good", because an unsurveyed site is indistinguishable from
# a current one in this data. See the generator docstring.
#
# Selecting a row sets varCustomer and hands off to scrCustomerOverview.

Screens:
  scrCustomers:
    Properties:
      Fill: =AppDark.Bg
    Children:
      - conRootCus:
          Control: GroupContainer
          Variant: ManualLayout
          Properties:
            X: =0
            Y: =0
            Width: =Parent.Width
            Height: =Parent.Height
            Fill: =AppDark.Bg
          Children:
{P.brand_band("Cus", "scrHome", back_transition="CoverRight", back_label="Home")}

            - lblTitleCus:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter
                  Y: ={P.BAND} + 24
                  Width: ={P.CW}
                  Height: =41
                  Text: ="Customers"
                  Font: =AppFont
                  Size: =If(IsNarrow, AppType.Title, AppType.Display)
                  FontWeight: =FontWeight.Semibold
                  Color: =AppDark.Fg
                  Wrap: =false
                  AutoHeight: =false
            # Says how many rows the search is showing, so an empty-looking list reads as a
            # narrow search rather than as missing data.
            - lblSubtitleCus:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter
                  Y: =lblTitleCus.Y + lblTitleCus.Height
                  Width: ={P.CW}
                  Height: =22
                  Font: =AppFont
                  Size: =AppType.Body
                  Color: =AppDark.FgSecondary
                  Wrap: =false
                  AutoHeight: =false
                  Text: |
                    =CountRows(galCustomers.AllItems) & If(Len(Trim(txtSearchCus.Text)) > 0, " matching", " active") & " site(s)"

            - txtSearchCus:
                Control: ModernTextInput
                Properties:
                  Type: =TextInputType.Search
                  X: =Gutter
                  Y: =lblSubtitleCus.Y + lblSubtitleCus.Height + Gutter
                  Width: =Min({P.CW}, {P.PANEL_MAX})
                  Height: =48
                  Default: =""
                  Placeholder: ="Search customers"
                  Font: =AppFont
                  Size: =AppType.Body
                  Color: =AppDark.Fg
                  Fill: =AppDark.Surface
                  BorderColor: =AppDark.Line
                  BorderThickness: =1
                  RadiusTopLeft: =6
                  RadiusTopRight: =6
                  RadiusBottomLeft: =6
                  RadiusBottomRight: =6

            - galCustomers:
                Control: Gallery
                Variant: Vertical
                Properties:
                  X: =Gutter
                  Y: =txtSearchCus.Y + txtSearchCus.Height + Gutter
                  Width: ={P.CW}
                  Height: =Max(Parent.Height - (txtSearchCus.Y + txtSearchCus.Height + Gutter) - Gutter, {CARD_H})
                  TemplateSize: ={CARD_H + 10}
                  TemplatePadding: =0
                  ShowScrollbar: =true
                  Items: |
                    =SortByColumns(
                        Filter(
                            TB_Customers,
                            Active = true,
                            StartsWith(Title, Trim(txtSearchCus.Text))
                        ),
                        "Title",
                        SortOrder.Ascending
                    )
                  OnSelect: |
                    =Set(varCustomer, ThisItem);
                    Navigate(scrCustomerOverview, ScreenTransition.Cover)
                Children:
                  - imgCardCus:
                      Control: Image
                      Properties:
                        X: =0
                        Y: =0
                        Width: =Parent.TemplateWidth
                        Height: ={CARD_H}
                        Image: |
                          ="data:image/svg+xml;utf8, " & EncodeUrl(
                              "<svg xmlns='http://www.w3.org/2000/svg' width='" & Round(Parent.TemplateWidth, 0) & "' height='{CARD_H}' viewBox='0 0 " & Round(Parent.TemplateWidth, 0) & " {CARD_H}' preserveAspectRatio='none'>" &
                              "<path d='M0 0 H" & Round(Parent.TemplateWidth - 14, 0) & " L" & Round(Parent.TemplateWidth, 0) & " 14 V{CARD_H} H0 Z' fill='#171A21' stroke='#2A2F3A' stroke-width='1'/>" &
                              "</svg>"
                          )
                  # BEHIND is a non-delegable Filter with a nested LookUp per installation,
                  # so it is evaluated ONCE per row here and read back by the two controls
                  # that need it. Referencing a sibling inside the same gallery template is
                  # row-scoped, which is the same hidden-label idiom used for ForAll over
                  # AllItems elsewhere in this app.
                  - lblBehindCalcCus:
                      Control: ModernText
                      Properties:
                        PaddingTop: =0
                        PaddingBottom: =0
                        OnSelect: =Select(Parent)
                        X: =0
                        Y: =0
                        Width: =1
                        Height: =1
                        Visible: =false
                        Font: =AppFont
                        Size: =AppType.Small
                        Color: =AppDark.Muted
                        Text: |
                          ={BEHIND}

                  # Amber only when something is known to be behind. Neutral otherwise -
                  # never green, because "nothing recorded" and "all current" are the same
                  # shape in this data and only one of them deserves reassurance.
                  - recCardRailCus:
                      Control: Rectangle
                      Properties:
                        OnSelect: =Select(Parent)
                        X: =0
                        Y: =0
                        Width: =4
                        Height: ={CARD_H}
                        Fill: |
                          =If(Value(lblBehindCalcCus.Text) > 0, AppDark.Warn, AppDark.Line)
                  - lblName:
                      Control: ModernText
                      Properties:
                        PaddingTop: =0
                        PaddingBottom: =0
                        OnSelect: =Select(Parent)
                        X: =20
                        Y: =14
                        Width: =(Parent.TemplateWidth - 40) * 0.68
                        Height: =26
                        Text: =ThisItem.Title
                        Font: =AppFont
                        Size: =AppType.Heading
                        FontWeight: =FontWeight.Semibold
                        Color: =AppDark.Fg
                        Wrap: =false
                        AutoHeight: =false
                  - lblDesc:
                      Control: ModernText
                      Properties:
                        PaddingTop: =0
                        PaddingBottom: =0
                        OnSelect: =Select(Parent)
                        X: =20
                        Y: =42
                        Width: =(Parent.TemplateWidth - 40) * 0.68
                        Height: =20
                        Font: =AppFont
                        Size: =AppType.Small
                        Color: =AppDark.Muted
                        Wrap: =false
                        AutoHeight: =false
                        Text: |
                          ={SOL_N} & " solution(s)" & If(IsBlank(ThisItem.Description), "", "  ·  " & ThisItem.Description)
                  # Conditional Text rather than Visible + Text: BEHIND is a non-delegable
                  # Filter with a nested LookUp per installation, and a separate Visible
                  # would evaluate it a third time on every row for no visual difference.
                  - lblBehindCus:
                      Control: ModernText
                      Properties:
                        PaddingTop: =0
                        PaddingBottom: =0
                        OnSelect: =Select(Parent)
                        X: =20 + ((Parent.TemplateWidth - 40) * 0.68)
                        Y: =28
                        Width: =(Parent.TemplateWidth - 40) * 0.32 - 10
                        Height: =22
                        Align: =Align.Right
                        Font: =AppFont
                        Size: =AppType.Body
                        FontWeight: =FontWeight.Semibold
                        Color: =AppDark.Warn
                        Wrap: =false
                        AutoHeight: =false
                        Text: |
                          =If(Value(lblBehindCalcCus.Text) > 0, lblBehindCalcCus.Text & " behind", "")
                  - galCustomersHit:
                      Control: Classic/Button
                      Properties:
                        OnSelect: =Select(Parent)
                        X: =0
                        Y: =0
                        Width: =Parent.TemplateWidth
                        Height: ={CARD_H}
                        Text: =""
                        Fill: =RGBA(0, 0, 0, 0)
                        HoverFill: =RGBA(106, 115, 230, 0.10)
                        PressedFill: =RGBA(106, 115, 230, 0.18)
                        BorderThickness: =0
                        HoverBorderColor: =RGBA(0, 0, 0, 0)
                        PressedBorderColor: =RGBA(0, 0, 0, 0)
                        FocusedBorderThickness: =2
                        FocusedBorderColor: =AppDark.Accent
            - lblNoCustomers:
                Control: ModernText
                Properties:
                  PaddingTop: =0
                  PaddingBottom: =0
                  X: =Gutter
                  Y: =galCustomers.Y
                  Width: ={P.CW}
                  Height: =40
                  Font: =AppFont
                  Size: =AppType.Body
                  Color: =AppDark.Muted
                  Visible: =CountRows(galCustomers.AllItems) = 0
                  Text: |
                    =If(Len(Trim(txtSearchCus.Text)) > 0, "No customers start with """ & Trim(txtSearchCus.Text) & """.", "No active customers are on file.")
'''

OUT.write_text(doc, encoding="utf-8", newline="")
print(f"wrote {OUT}  ({len(doc.splitlines())} lines)")
