"""Generate scrEditForm.pa.yaml (and patch scrAdmin to match).

Four typed record variables - varRecCust / varRecProd / varRecInst / varRecRef -
rather than one polymorphic varAdminRecord. Power Fx infers a variable's type
from its Set() calls, and a single variable Set to records of four different
tables has no coherent type. Defaults(<table>) gives an empty record WITH a
schema, the same reason App.OnStart uses it instead of Blank().
"""

import screen_parts as P
import io, sys, importlib.util, re

import os
spec = importlib.util.spec_from_file_location(
    "g", os.path.join(os.path.dirname(os.path.abspath(__file__)), "gen_admin.py"))
# gen_admin writes a file on import; re-exec just for LISTS is fine
g = importlib.util.module_from_spec(spec); spec.loader.exec_module(g)
LISTS, fid = g.LISTS, g.fid

def prop(o, k, v, ind):
    # A ": " inside a Power Fx value terminates the YAML key when written
    # inline. Emit those as block scalars. See gen_onboard.py for the full note.
    if ": " in v:
        o.write(f"{ind}{k}: |\n{ind}  ={v}\n")
    else:
        o.write(f"{ind}{k}: ={v}\n")
def blk(o, k, lines, ind):
    o.write(f"{ind}{k}: |\n")
    for i, l in enumerate(lines):
        o.write(f"{ind}  {'=' if i == 0 else ''}{l}\n")
def ctrl(o, name, control, ind, variant=None):
    o.write(f"{ind}- {name}:\n{ind}    Control: {control}\n")
    if variant: o.write(f"{ind}    Variant: {variant}\n")
    o.write(f"{ind}    Properties:\n")
    return ind + "      "

def var(L): return "varRec" + L["key"]

def input_name(L, f): return {"text":"txt","note":"txt","url":"txt","choice":"dd","bool":"tgl","lookup":"dd"}[f["kind"]] + fid(f) + L["key"]

# value written by Patch for one field
def patch_value(L, f):
    n, k = input_name(L, f), f["kind"]
    if k in ("text", "note", "url"): return f"{n}.Text"
    if k == "bool":                  return f"{n}.Checked"
    if k == "choice":                return f"{{ Value: {n}.Selected.Value }}"
    if k == "lookup":
        # Choices() already returns records in the shape the lookup accepts.
        return f"If(IsBlank({n}.Selected), Blank(), {n}.Selected)"
    raise ValueError(k)

# Default shown in the input when editing an existing record
def default_expr(L, f):
    v, n = var(L), f["n"]
    k = f["kind"]
    if k in ("text", "note", "url"): return f'If(varAdminNew, "", {v}.{n})'
    if k == "bool":                  return f"If(varAdminNew, false, {v}.{n})"
    if k == "choice":                return f'If(varAdminNew, "", {v}.{n}.Value)'
    if k == "lookup":                return f'If(varAdminNew, "", {v}.{n}.Value)'

def default_record_expr(L, f):
    """Preselection for a ModernDropdown, whose Default is a Record.

    The classic control took the display Text, so an edit could just hand it
    the stored value. A record has to be found in the same option set the
    control is showing, hence the LookUp by Value.
    """
    v, n = var(L), f["n"]
    return (f"If(varAdminNew, Blank(), "
            f"LookUp(Choices({L['source']}.{n}), Value = {v}.{n}.Value))")


def default_items_expr(L, f):
    """ComboBox preselection for edit mode.

    DefaultSelectedItems takes a Table, and a SharePoint lookup projects as
    {Id, Value} -- which is not a row of the target list -- so the row has to be
    fetched back by Id rather than handed over directly.
    """
    v, n, t = var(L), f["n"], f["target"]
    return f"If(varAdminNew, Blank(), Filter({t}, ID = {v}.{n}.Id))"

def items_expr(L, f):
    if f["kind"] == "choice":
        return f"Choices({L['source']}.{f['n']})"
    if f.get("parent"):
        # Choices() gives lookup-shaped {Id, Value} records but carries no other
        # columns, so the customer scoping has to be applied by intersecting on
        # Id with the rows that qualify. IsBlank('Parent') is the runtime-verified
        # form - see app/00_Setup.md.
        # Choices() yields {Id, Value} and carries no other columns, so the
        # customer scoping is applied by asking, for each option, whether a
        # qualifying row exists. "As Opt" names the outer scope so Opt.Id is not
        # shadowed by TB_Installations' own columns in the inner Filter.
        return ("Filter(Choices(TB_Installations.'Parent') As Opt, "
                "CountRows(Filter(TB_Installations, ID = Opt.Id, "
                "Customer.Id = ddCustomerInst.Selected.Id, IsBlank('Parent'))) > 0)")
    return f"Choices({L['source']}.{f['n']})"

# ------------------------------------------------------------------ generate
o = io.StringIO()
o.write("# Generated by scripts/gen_form.py - create / edit any TB_* record.\n"
        "# Deliberately built from Classic inputs + Patch(), NOT Form + SubmitForm:\n"
        "# describe_control returns HTTP 500 for Form and DataCard, so their\n"
        "# properties cannot be verified and must not be guessed at.\n"
        "Screens:\n  scrEditForm:\n    Properties:\n      Fill: =AppDark.Bg\n"
        "      OnVisible: =Set(varConfirmDelete, false)\n"
        "    Children:\n")
ind = "      "
p = ctrl(o, "conRootEdit", "GroupContainer", ind, "ManualLayout")
for k, v in [("Fill","AppDark.Bg"),("Height","Parent.Height"),("Width","ContentWidth"),
             ("X","Max((Parent.Width - ContentWidth) / 2, Gutter)")]: prop(o, k, v, p)
o.write(f"{p[:-2]}Children:\n"); c = p
o.write(P.brand_band("Edit", "scrAdmin", back_transition="UnCoverRight", back_label="Admin") + "\n")

q = ctrl(o, "btnBackEdit", "Classic/Button", c)
for k, v in [("BorderThickness","0"),("Color","AppDark.Accent"),("Fill","AppDark.Bg"),
             ("Font","AppFont"),("Height","44"),("HoverColor","AppDark.AccentSolid"),
             ("HoverFill","AppDark.Sunken"),
             ("OnSelect","Navigate(scrAdmin, ScreenTransition.CoverRight)"),
             ("Size","AppType.Small"),("Text",'"<  Cancel"'),("Width","Gutter * 8"),
             ("X","Gutter"),("Y","56 + Gutter"),("FocusedBorderThickness","2"),
             ("FocusedBorderColor","AppDark.Accent")]: prop(o, k, v, q)

q = ctrl(o, "lblTitleEdit", "Label", c)
title = ('If(varAdminNew, "New ", "Edit ") & Switch(varAdminList, '
         + ", ".join(f'"{L["key"]}", "{L["label"][:-1].lower()}"' for L in LISTS) + ', "record")')
for k, v in [("Color","AppDark.Fg"),("Font","AppFont"),("FontWeight","FontWeight.Bold"),
             ("Height","36"),("Size","AppType.Title"),("Text",title),("Wrap","false"),
             ("AutoHeight","false"),("Width","ContentWidth - (Gutter * 2)"),
             ("X","Gutter"),("Y","56 + Gutter + 34")]: prop(o, k, v, q)

# ---- fields, grouped per list, only the selected list visible
for L in LISTS:
    y = 120
    vis = f'varAdminList = "{L["key"]}"'
    for f in L["fields"]:
        nm, k = input_name(L, f), f["kind"]
        cap = ctrl(o, "lblCap" + fid(f) + L["key"], "Label", c)
        for kk, vv in [("Text",f'"{f["caption"]}"'),("Color","AppDark.Muted"),
                       ("Font","AppFont"),("Size","AppType.Small"),
                       ("FontWeight","FontWeight.Semibold"),("Wrap","false"),
                       ("AutoHeight","false"),("Height","18"),
                       ("Width","ContentWidth - (Gutter * 2)"),("X","Gutter"),
                       ("Y",str(y)),("Visible",vis)]: prop(o, kk, vv, cap)
        h = 64 if k == "note" else 40
        if k in ("text","note","url"):
            i = ctrl(o, nm, "Classic/TextInput", c)
            for kk, vv in [("Default",default_expr(L,f)),("Mode",
                            "TextMode.MultiLine" if k=="note" else "TextMode.SingleLine"),
                           ("HintText",'""'),("BorderColor","AppDark.Line"),
                           ("BorderThickness","1"),("Color","AppDark.Fg"),
                           ("Fill","AppDark.Surface"),("Font","AppFont"),
                           ("Size","AppType.Body"),("Height",str(h)),
                           ("Width","ContentWidth - (Gutter * 2)"),("X","Gutter"),
                           ("Y",str(y+18)),("Visible",vis),
                           ("RadiusTopLeft","6"),("RadiusTopRight","6"),
                           ("RadiusBottomLeft","6"),("RadiusBottomRight","6")]: prop(o, kk, vv, i)
        elif k == "bool":
            # TrueFill / FalseFill do not exist on ModernToggle - the theme
            # paints it. Its output is Checked, which patch_value() reads.
            i = ctrl(o, nm, "ModernToggle", c)
            for kk, vv in [("Default",default_expr(L,f)),("Font","AppFont"),
                           ("Size","AppType.Body"),("Height","36"),("Width","110"),
                           ("X","Gutter"),("Y",str(y+18)),("Visible",vis)]: prop(o, kk, vv, i)
            h = 36
        elif k == "choice":
            i = ctrl(o, nm, "ModernDropdown", c)
            o.write(f"{i}Items: |\n{i}  ={items_expr(L,f)}\n")
            for kk, vv in [("Default",default_record_expr(L,f)),
                           ("ItemDisplayText","ThisItem.Value"),
                           ("BorderColor","AppDark.Line"),("BorderThickness","1"),
                           ("Color","AppDark.Fg"),("Fill","AppDark.Surface"),
                           ("Font","AppFont"),("Size","AppType.Body"),("Height","40"),
                           ("Width","ContentWidth - (Gutter * 2)"),("X","Gutter"),
                           ("Y",str(y+18)),("Visible",vis)]: prop(o, kk, vv, i)
        else:
            # Lookups use a Drop down with an explicit Value column.
            #
            # Per the Drop down control reference: "Items - The source of data
            # that contains the items that appear in the control. If the source
            # has multiple columns, set the control's Value property to the
            # column of data that you want to show." A SharePoint list is always
            # multi-column, so without Value the control has no display column
            # and renders an empty list.
            #
            # Note describe_control does not return Value among Classic/DropDown's
            # input properties, though the documentation lists it as a key one.
            #
            # ComboBox was tried and abandoned: Studio seeds it with a SearchItems
            # default of Search(ComboBoxSample, ..., "Value1"), a sample source
            # that does not exist here, and that property cannot be overridden
            # from YAML ("Unknown property 'SearchItems'"). IsSearchable: =false
            # does not stop it being evaluated either.
            i = ctrl(o, nm, "ModernDropdown", c)
            o.write(f"{i}Items: |\n{i}  ={items_expr(L,f)}\n")
            for kk, vv in [("Default",default_record_expr(L,f)),
                           ("ItemDisplayText","ThisItem.Value"),
                           ("BorderColor","AppDark.Line"),("BorderThickness","1"),
                           ("Color","AppDark.Fg"),("Fill","AppDark.Surface"),
                           ("Font","AppFont"),("Size","AppType.Body"),("Height","40"),
                           ("Width","ContentWidth - (Gutter * 2)"),("X","Gutter"),
                           ("Y",str(y+18)),("Visible",vis)]: prop(o, kk, vv, i)
        y += 18 + h + 14

# ---- save
q = ctrl(o, "btnSaveEdit", "Classic/Button", c)
lines = ["IfError("]
for idx, L in enumerate(LISTS):
    # each assignment must be its own entry: blk() prefixes per line, so a
    # multi-line string here would leave later lines under-indented and
    # silently terminate the YAML block scalar.
    fl = [f"                {f['n']}: {patch_value(L, f)}" for f in L["fields"]]
    fl = [x + ("," if i < len(fl) - 1 else "") for i, x in enumerate(fl)]
    lines += [f'    If(varAdminList = "{L["key"]}",',
              f"        Patch({L['source']},",
              f"            If(varAdminNew, Defaults({L['source']}), {var(L)}),",
              "            {"] + fl + [
              "            }",
              "        )",
              "    );"]
lines += ['    Set(varEditError, "");',
          "    Navigate(scrAdmin, ScreenTransition.UnCoverRight),",
          "    Set(varEditError, FirstError.Message)",
          ")"]
blk(o, "OnSelect", lines, q)
for k, v in [("Font","AppFont"),("Size","AppType.Body"),("FontWeight","FontWeight.Semibold"),
             ("Text",'"Save"'),("Fill","AppDark.Accent"),("Color","AppDark.OnBrand"),
             ("HoverFill","AppDark.AccentSolid"),("BorderThickness","0"),
             ("Height","44"),("Width","160"),("X","Gutter"),
             ("Y","Parent.Height - Gutter - 44"),
             ("RadiusTopLeft","6"),("RadiusTopRight","6"),
             ("RadiusBottomLeft","6"),("RadiusBottomRight","6"),
             ("FocusedBorderThickness","2"),("FocusedBorderColor","AppDark.Accent")]: prop(o, k, v, q)

# ---- delete
# Only for an existing record, and only when nothing points at it. SharePoint
# lookups do not cascade: deleting a product referenced by an installation
# leaves that installation with a required column pointing at nothing, which is
# worse than refusing.
# One line. prop() writes a value inline, and an embedded newline ends the YAML
# key early - the same trap as an inline ": ", and it fails the same way, with a
# parse error hundreds of lines from the cause. Long but generated, not read.
DEPS = "Switch(varAdminList, " + ", ".join(
    f'"{L["key"]}", {L["deps"]}' for L in LISTS if L.get("deps")) + ", 0)"
DEPSLABEL = 'Switch(varAdminList, ' + ", ".join(
    f'"{L["key"]}", "{L["depsLabel"]}"' for L in LISTS if L.get("deps")) + ', "")'

q = ctrl(o, "lblDeleteBlocked", "Label", c)
blocked = (f'"Cannot delete: " & ({DEPS}) & " " & ({DEPSLABEL}) & '
           '" still reference this. Remove those first."')
for k, v in [("Text",blocked),("Color","AppDark.Danger"),("Font","AppFont"),
             ("Size","AppType.Small"),("Wrap","true"),("AutoHeight","false"),
             ("Align","Align.Right"),("Height","36"),
             ("Width","ContentWidth - (Gutter * 2) - 360"),
             ("X","Gutter + 360"),("Y","Parent.Height - Gutter - 88"),
             ("Visible",f"!varAdminNew && ({DEPS}) > 0")]: prop(o, k, v, q)

q = ctrl(o, "btnDeleteEdit", "Classic/Button", c)
# Notify rather than a label. A delete either happens or it does not, and the
# first version reported failure into lblEditError, which sits along the bottom
# where these buttons now are - so a real error could render behind them and
# look like nothing happening at all.
#
# Refresh after Remove because the gallery on scrAdmin reads a filtered view of
# the same source, and without it the row can survive the trip back.
blk(o, "OnSelect", [
    "If(!varConfirmDelete,",
    "    Set(varConfirmDelete, true),",
    "    IfError(",
    "        Switch(varAdminList,"] + [
    f'            "{L["key"]}", Remove({L["source"]}, {var(L)}); Refresh({L["source"]}),'
    for L in LISTS] + [
    "            Notify(\"Nothing was selected to delete.\", NotificationType.Error)",
    "        );",
    '        Set(varConfirmDelete, false);',
    '        Notify("Deleted.", NotificationType.Success);',
    "        Navigate(scrAdmin, ScreenTransition.UnCoverRight),",
    '        Notify("Could not delete: " & FirstError.Message, NotificationType.Error);',
    "        Set(varConfirmDelete, false)",
    "    )",
    ")"], q)
for k, v in [("Font","AppFont"),("Size","AppType.Body"),("FontWeight","FontWeight.Semibold"),
             ("Text",'If(varConfirmDelete, "Confirm delete", "Delete")'),
             # No Fill or Color here. ModernButton has no Fill, so the conversion
             # drops it - but Color survives, and a Color that only made sense
             # against the dropped Fill left white text on a light button.
             # Appearance and BasePaletteColor carry both states instead; see
             # EXTRA in scripts/modernize.py.
             ("BorderThickness","1"),
             ("Height","44"),("Width","170"),
             ("X","ContentWidth - Gutter - 170"),
             ("Y","Parent.Height - Gutter - 44"),
             ("RadiusTopLeft","6"),("RadiusTopRight","6"),
             ("RadiusBottomLeft","6"),("RadiusBottomRight","6"),
             ("Visible",f"!varAdminNew && ({DEPS}) = 0"),
             ("FocusedBorderThickness","2"),
             ("FocusedBorderColor","AppDark.Danger")]: prop(o, k, v, q)

q = ctrl(o, "btnCancelDelete", "Classic/Button", c)
for k, v in [("Font","AppFont"),("Size","AppType.Small"),("Text",'"Cancel"'),
             ("Fill","AppDark.Surface"),("Color","AppDark.Fg"),
             ("HoverFill","AppDark.Sunken"),
             ("BorderColor","AppDark.Line"),("BorderThickness","1"),
             ("Height","44"),("Width","110"),
             ("X","ContentWidth - Gutter - 170 - 8 - 110"),
             ("Y","Parent.Height - Gutter - 44"),
             ("RadiusTopLeft","6"),("RadiusTopRight","6"),
             ("RadiusBottomLeft","6"),("RadiusBottomRight","6"),
             ("OnSelect","Set(varConfirmDelete, false)"),
             ("Visible","varConfirmDelete")]: prop(o, k, v, q)

q = ctrl(o, "lblEditError", "Label", c)
# AppTheme on this branch has Warn / WarnLight but no Danger slot, so the
# save-failure message uses an explicit error red rather than an amber.
for k, v in [("Text","varEditError"),("Color","AppDark.Danger"),("Font","AppFont"),
             ("Size","AppType.Small"),("Wrap","true"),("AutoHeight","false"),
             ("Height","44"),("Width","ContentWidth - (Gutter * 2) - 176"),
             ("X","Gutter + 176"),("Y","Parent.Height - Gutter - 44"),
             ("Visible","!IsBlank(varEditError)")]: prop(o, k, v, q)


# The generators emit classic controls; modernize.py owns the single mapping to
# their Fluent equivalents, so regenerating never silently reverts a screen.
import importlib.util as _ilu, os as _os
_spec = _ilu.spec_from_file_location(
    "modernize", _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), "modernize.py"))
_mz = _ilu.module_from_spec(_spec); _spec.loader.exec_module(_mz)

def _modern(src):
    src, rep = _mz.modernize_source(src)
    for line in rep:
        print(line)
    return src


open(r"E:\Papp\powerappgoofing\app\screens\scrEditForm.pa.yaml", "w", encoding="utf-8", newline="").write(_modern(o.getvalue()))
print("wrote scrEditForm.pa.yaml")
